# ToDo

* Verificar que las coops reportadas en la SuperSolidaria se encuentren dentro de los datos extraidos del web scraping
* Filtrar dichas coops en el rango de años donde tengan los datos completos (idealmente entre 2022-2025)
* Generar dataset con las coops/datos filtradas para generar el CAMEL nuevamente

Leer coops de la info de la SuperSolidaria

In [1]:
import pandas as pd

cacs = pd.read_excel("../../tablas/listado_entidades_CACs.xlsx")
cacs

,CODENTIDAD,ÚLTIMA FECHA DE REPORTE,NOMBREENTIDAD,SIGLA,ESTADO,NOMBRETIPO,CATEGORIA
0,90,2026-07-31,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPCAFAM,Normal,Especializada de ahorro y credito,CACs
1,93,2026-07-31,COOPERATIVA DE TRABAJADORES DE LA INDUSTRIA M...,COOPINDUMIL,Normal,Multiactiva con ahorro y credito,CACs
2,124,2026-07-31,COOPERATIVA DEL SISTEMA NACIONAL DE JUSTICIA,JURISCOOP,Normal,Especializada de ahorro y credito,CACs
3,127,2026-07-31,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,COASMEDAS,Normal,Especializada de ahorro y credito,CACs
4,197,2026-07-31,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENES...,BENEFICIAR,Normal,Especializada de ahorro y credito,CACs
...,...,...,...,...,...,...,...
170,13022,2026-06-30,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,AFROAMERICANA,Normal,Especializada de ahorro y credito,CACs
171,13024,2026-07-31,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,COOPCANAPRO,Normal,Especializada de ahorro y credito,CACs
172,13813,2026-06-30,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,FINANCIERA SUCREDITO,Normal,Especializada de ahorro y credito,CACs
173,15236,2026-07-31,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,CREDIAHORROS TAX LA FERIA,Normal,Especializada de ahorro y credito,CACs
174,20009,2026-07-31,COOPERATIVA DE AHORRO Y CREDITO SUYA LTDA,COOPSUYA,Normal,Especializada de ahorro y credito,CACs

Leer datos del web scraping 2013-2025

In [2]:
data = pd.read_csv("../../tablas/Datos_2013_2025_cooperativas.csv")
data

,CUENTA,NOMBRE CUENTA,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE TRABAJADORES DE LA INDUSTRIA MILITAR,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,...,COOPERATIVA DE AHORRO Y CREDITO INTEGRAR,COOPERATIVA MULTIACTIVA DE APORTE Y CREDITO,MICROEMPRESAS DE ANTIOQUIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,COOPERATIVA MULTIACTIVA UNION DE COMERCIANTES PLAZA TRINIDAD GALAN,FONDO DE EMPLEADOS DEL MINISTERIO DEL INTERIOR,COOPERATIVA AVANZA,COOPERATIVA MULTIACTIVA UNION COLOMBIANA,PRECOOPERATIVA PARA EL FOMENTO Y DESARROLLO DE LAS ACTIVIDADES MINERAS,DATE
0,100000,ACTIVO,1.453604e+11,1.204461e+10,3.387150e+11,1.560676e+11,9.879448e+10,1.064674e+10,7.021719e+10,3.751248e+10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01
1,110000,EFECTIVO Y EQUIVALENTE AL EFECTIVO,1.094558e+10,1.108710e+09,1.566943e+10,2.669495e+10,1.918907e+09,1.552585e+09,4.685907e+09,1.926925e+09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01
2,110500,CAJA,2.868046e+08,1.061263e+07,8.229352e+08,1.100000e+06,3.589941e+08,1.718631e+08,1.241549e+08,8.000000e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01
3,110505,CAJA GENERAL,2.791246e+08,1.061263e+07,8.180852e+08,0.000000e+00,3.589941e+08,1.718631e+08,1.146549e+08,0.000000e+00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01
4,110510,CAJA MENOR,7.680000e+06,0.000000e+00,4.850000e+06,1.100000e+06,0.000000e+00,0.000000e+00,9.500000e+06,8.000000e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320450,935000,OTRAS ACREEDORAS DE CONTROL,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.900000e+01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.0,2014-12-01
320451,960000,ACREEDORAS CONTINGENTES POR CONTRA,NaN,7.286149e+09,2.645291e+11,1.493243e+08,5.438012e+10,2.747754e+09,4.058720e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.970617e+10,2.208899e+10,34000000.0,2014-12-01
320452,960500,ACREEDORAS CONTINGENTES POR CONTRA (DB),NaN,7.286149e+09,2.645291e+11,1.493243e+08,5.438012e+10,2.747754e+09,4.058720e+10,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6.970617e+10,2.208899e+10,34000000.0,2014-12-01
320453,980000,ACREEDORAS DE CONTROL POR CONTRA,NaN,1.274480e+09,2.619920e+10,3.159206e+11,7.700000e+09,1.299760e+09,6.160000e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.596689e+09,2.710400e+09,0.0,2014-12-01
320454,980500,ACREEDORAS DE CONTROL POR CONTRA (DB),NaN,1.274480e+09,2.619920e+10,3.159206e+11,7.700000e+09,1.299760e+09,6.160000e+09,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.596689e+09,2.710400e+09,0.0,2014-12-01

Revisar las cooperativas que no se encuentran de la lista, y hacer ajustes de algunos nombres:

In [3]:
data["COPERATIVA  ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"] = data["COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"].combine_first(data["COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"])
data["COOPERATIVA DE AHORRO Y CREDITO FINCOMERCIO LTDA"] = data["COOPERATIVA DE AHORRO Y CR??DITO FINCOMERCIO LTDA"].combine_first(data["COOPERATIVA DE AHORRO Y CRÉDITO FINCOMERCIO LTDA"])
data["COOPERATIVA JUDICIAL  DEL TOLIMA  LTDA"] = data["COOPERATIVA JUDICIAL DEL TOLIMA"].combine_first(data["COOPERATIVA JUDICIAL DEL TOLIMA LTDA"])
data["COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE  LTDA"] = data["COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE"].combine_first(data["COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE LTDA"])
data["ORGANIZACION COOPERATIVA DE AHORRO Y CREDITO NORTE DE BOYACA"] = data["ORGANIZACION COOPERATIVA DE AHORRO Y CR??DITO NORTE DE BOYACA"].combine_first(data["COOPERATIVA MULTIACTIVA DEL NORTE DE BOYACA"])
data["COOPERATIVA ANTIOQUEYA DE TRABAJADORES GRUPO CAFETERO"] = data["COOPERATIVA ANTIOQUEÑA DE TRABAJADORES GRUPO CAFETERO"].combine_first(data["COOPERATIVA ANTIOQUE¥A DE TRABAJADORES GRUPO CAFETERO"]).combine_first(data["COOPERATIVA ANTIOQUE??A DE TRABAJADORES GRUPO CAFETERO"])
data["PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CREDITO"] = data["PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CR??DITO"].combine_first(data["PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CRÉDITO"])

C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["COPERATIVA  ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"] = data["COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"].combine_first(data["COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"])
C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["COOPERATIVA DE AHORRO Y CREDITO FINCOMERCIO LTDA"] = data["COOPERATIVA DE AHORRO Y CR??DITO FINCOMERCIO LTDA"].combine_first(data["COOPERATIVA DE AHORRO Y CRÉDITO FINCOMERCIO LTDA"])
C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["COOPERATIVA JUDICIAL  DEL TOLIMA  LTDA"] = data["COOPERATIVA JUDICIAL DEL TOLIMA"].combine_first(data["COOPERATIVA JUDICIAL DEL TOLIMA LTDA"])
C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE  LTDA"] = data["COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE"].combine_first(data["COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE LTDA"])
C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["ORGANIZACION COOPERATIVA DE AHORRO Y CREDITO NORTE DE BOYACA"] = data["ORGANIZACION COOPERATIVA DE AHORRO Y CR??DITO NORTE DE BOYACA"].combine_first(data["COOPERATIVA MULTIACTIVA DEL NORTE DE BOYACA"])
C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["COOPERATIVA ANTIOQUEYA DE TRABAJADORES GRUPO CAFETERO"] = data["COOPERATIVA ANTIOQUEÑA DE TRABAJADORES GRUPO CAFETERO"].combine_first(data["COOPERATIVA ANTIOQUE¥A DE TRABAJADORES GRUPO CAFETERO"]).combine_first(data["COOPERATIVA ANTIOQUE??A DE TRABAJADORES GRUPO CAFETERO"])
C:\Users\Liana\AppData\Local\Temp\ipykernel_8332\3898386629.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  data["PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CREDITO"] = data["PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CR??DITO"].combine_first(data["PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CRÉDITO"])

In [4]:
cacs.loc[
    cacs["NOMBREENTIDAD"] == "COPERATIVA  ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO",
    "NOMBREENTIDAD"
] = "COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO"

cacs.loc[
    cacs["NOMBREENTIDAD"] == "COOPERATIVA JUDICIAL  DEL TOLIMA  LTDA",
    "NOMBREENTIDAD"
] = "COOPERATIVA JUDICIAL DEL TOLIMA LTDA"

cacs.loc[
    cacs["NOMBREENTIDAD"] == "COOPERATIVA DE  TRABAJADORES DE LA INDUSTRIA MILITAR",
    "NOMBREENTIDAD"
] = "COOPERATIVA DE TRABAJADORES DE LA INDUSTRIA MILITAR"

cacs.loc[
    cacs["NOMBREENTIDAD"] == "COOPERATIVA DE AHORRO Y CREDITO VALLE DE SAN JOSE  LTDA",
    "NOMBREENTIDAD"
] = "COOPERATIVA DE AHORRO Y CREDITO VALLE DE SAN JOSE LTDA"
cacs.loc[
    cacs["NOMBREENTIDAD"] == "COOPERATIVA ANTIOQUEYA DE TRABAJADORES GRUPO CAFETERO",
    "NOMBREENTIDAD"
] = "COOPERATIVA ANTIOQUEÑA DE TRABAJADORES GRUPO CAFETERO"

In [5]:
# Renombrar columnas específicas
data = data.rename(columns={'COOPERATIVA DE AHORRO Y CREDITO COOPSERVUNAL': 'COOPERATIVA DE AHORRO Y CREDITO COOSERVUNAL',
                            'COOPERATIVA DE AHORRO Y CR??DITO SANTA ROSA DE OSOS LIMITADA': 'COOPERATIVA DE AHORRO Y CREDITO SANTA ROSA DE OSOS LIMITADA',
                            'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DE LA ORGANIZACI??N CARVAJAL': 'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DE LA ORGANIZACION CARVAJAL',
                            'MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA': 'EL ROBLE ENTIDAD COOPERATIVA',
                            'COOPERATIVA DE TRABAJADORES DE ENKA LTDA': 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO COOPERENKA',
                            'COOPERATIVA DE AHORRO Y CREDITO DE LOS TRABAJADORES DEL SECTOR EDUCATIVO DE COLOMBIA LTDA': 'COOPERATIVA DE AHORRO Y CREDITO DE LOS TRABAJADORES DEL SECTOR EDUCATIVO'})

In [6]:
# Nombres de cooperativas del primer dataframe
nombres_cooperativas = cacs["NOMBREENTIDAD"].dropna().tolist()

# Columnas del segundo dataframe
columnas_data = data.columns.tolist()

# Nombres que NO están en las columnas de data
no_encontradas = [
    nombre for nombre in nombres_cooperativas
    if nombre not in columnas_data
]

# Imprimirlas
for nombre in no_encontradas:
    print(nombre)

COOPERATIVA MULTIACTIVA UNIVERSITARIA NACIONAL

Eliminar esa cooperativa de la lista general porque no se encontró en el web scraping

In [7]:
nombres_cooperativas.remove("COOPERATIVA MULTIACTIVA UNIVERSITARIA NACIONAL")

**Filtrar las cooperativas que tengan los años completos 2022-2025**

In [8]:
cols_data_filt = nombres_cooperativas + ['CUENTA', 'NOMBRE CUENTA', 'DATE']
data_filt = data[cols_data_filt]

In [9]:
data_filt = data_filt[data_filt["DATE"] >= "2022-01-01"]
data_filt

,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE TRABAJADORES DE LA INDUSTRIA MILITAR,COOPERATIVA DEL SISTEMA NACIONAL DE JUSTICIA,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CREDITO,...,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO CAJA UNION,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO TAX LA FERIA,COOPERATIVA DE AHORRO Y CREDITO SUYA LTDA,CUENTA,NOMBRE CUENTA,DATE
0,1.453604e+11,1.204461e+10,NaN,3.387150e+11,1.560676e+11,9.879448e+10,1.064674e+10,7.021719e+10,3.751248e+10,2.452617e+11,...,1.964690e+11,NaN,7.498950e+09,NaN,7.673873e+10,3.689148e+10,NaN,100000,ACTIVO,2022-12-01
1,1.094558e+10,1.108710e+09,NaN,1.566943e+10,2.669495e+10,1.918907e+09,1.552585e+09,4.685907e+09,1.926925e+09,7.286577e+09,...,1.904275e+10,NaN,5.507006e+08,NaN,2.782317e+09,5.564935e+09,NaN,110000,EFECTIVO Y EQUIVALENTE AL EFECTIVO,2022-12-01
2,2.868046e+08,1.061263e+07,NaN,8.229352e+08,1.100000e+06,3.589941e+08,1.718631e+08,1.241549e+08,8.000000e+05,2.090386e+08,...,2.193096e+09,NaN,4.744467e+08,NaN,2.018711e+08,1.615997e+08,NaN,110500,CAJA,2022-12-01
3,2.791246e+08,1.061263e+07,NaN,8.180852e+08,0.000000e+00,3.589941e+08,1.718631e+08,1.146549e+08,0.000000e+00,2.080386e+08,...,2.182646e+09,NaN,4.738467e+08,NaN,1.998711e+08,1.600997e+08,NaN,110505,CAJA GENERAL,2022-12-01
4,7.680000e+06,0.000000e+00,NaN,4.850000e+06,1.100000e+06,0.000000e+00,0.000000e+00,9.500000e+06,8.000000e+05,1.000000e+06,...,1.045000e+07,NaN,6.000000e+05,NaN,2.000000e+06,1.500000e+06,NaN,110510,CAJA MENOR,2022-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265561,0.000000e+00,0.000000e+00,NaN,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,931500,BIENES Y VALORES RECIBIDOS EN ADMINISTRACIÓN,2022-09-01
265562,0.000000e+00,0.000000e+00,NaN,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,NaN,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,931505,CARTERA FOGACOOP,2022-09-01
265563,7.498403e+09,1.029522e+10,NaN,4.308271e+11,2.173890e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,4.281462e+11,...,1.410674e+11,NaN,6.967973e+09,NaN,7.480500e+08,0.000000e+00,NaN,960000,ACREEDORAS POR CONTRA (DB),2022-09-01
265564,7.498403e+09,1.029522e+10,NaN,4.308271e+11,2.173890e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,4.281462e+11,...,1.410674e+11,NaN,6.967973e+09,NaN,7.480500e+08,0.000000e+00,NaN,960500,RESPONSABILIDADES CONTINGENTES POR EL CONTRARIO,2022-09-01
265565,2.103902e+09,0.000000e+00,NaN,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+10,3.200000e+09,5.359200e+10,...,8.902908e+06,NaN,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,980000,ACREEDORAS DE CONTROL POR CONTRA (CR),2022-09-01

Llenar valor NaN con ceros

In [10]:
data_filt.fillna(0, inplace=True)

,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE TRABAJADORES DE LA INDUSTRIA MILITAR,COOPERATIVA DEL SISTEMA NACIONAL DE JUSTICIA,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,PROGRESSA ENTIDAD COOPERATIVA DE AHORRO Y CREDITO,...,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO CAJA UNION,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO TAX LA FERIA,COOPERATIVA DE AHORRO Y CREDITO SUYA LTDA,CUENTA,NOMBRE CUENTA,DATE
0,1.453604e+11,1.204461e+10,0.0,3.387150e+11,1.560676e+11,9.879448e+10,1.064674e+10,7.021719e+10,3.751248e+10,2.452617e+11,...,1.964690e+11,0.0,7.498950e+09,0.0,7.673873e+10,3.689148e+10,0.0,100000,ACTIVO,2022-12-01
1,1.094558e+10,1.108710e+09,0.0,1.566943e+10,2.669495e+10,1.918907e+09,1.552585e+09,4.685907e+09,1.926925e+09,7.286577e+09,...,1.904275e+10,0.0,5.507006e+08,0.0,2.782317e+09,5.564935e+09,0.0,110000,EFECTIVO Y EQUIVALENTE AL EFECTIVO,2022-12-01
2,2.868046e+08,1.061263e+07,0.0,8.229352e+08,1.100000e+06,3.589941e+08,1.718631e+08,1.241549e+08,8.000000e+05,2.090386e+08,...,2.193096e+09,0.0,4.744467e+08,0.0,2.018711e+08,1.615997e+08,0.0,110500,CAJA,2022-12-01
3,2.791246e+08,1.061263e+07,0.0,8.180852e+08,0.000000e+00,3.589941e+08,1.718631e+08,1.146549e+08,0.000000e+00,2.080386e+08,...,2.182646e+09,0.0,4.738467e+08,0.0,1.998711e+08,1.600997e+08,0.0,110505,CAJA GENERAL,2022-12-01
4,7.680000e+06,0.000000e+00,0.0,4.850000e+06,1.100000e+06,0.000000e+00,0.000000e+00,9.500000e+06,8.000000e+05,1.000000e+06,...,1.045000e+07,0.0,6.000000e+05,0.0,2.000000e+06,1.500000e+06,0.0,110510,CAJA MENOR,2022-12-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265561,0.000000e+00,0.000000e+00,0.0,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,931500,BIENES Y VALORES RECIBIDOS EN ADMINISTRACIÓN,2022-09-01
265562,0.000000e+00,0.000000e+00,0.0,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,931505,CARTERA FOGACOOP,2022-09-01
265563,7.498403e+09,1.029522e+10,0.0,4.308271e+11,2.173890e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,4.281462e+11,...,1.410674e+11,0.0,6.967973e+09,0.0,7.480500e+08,0.000000e+00,0.0,960000,ACREEDORAS POR CONTRA (DB),2022-09-01
265564,7.498403e+09,1.029522e+10,0.0,4.308271e+11,2.173890e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,4.281462e+11,...,1.410674e+11,0.0,6.967973e+09,0.0,7.480500e+08,0.000000e+00,0.0,960500,RESPONSABILIDADES CONTINGENTES POR EL CONTRARIO,2022-09-01
265565,2.103902e+09,0.000000e+00,0.0,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+10,3.200000e+09,5.359200e+10,...,8.902908e+06,0.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.0,980000,ACREEDORAS DE CONTROL POR CONTRA (CR),2022-09-01

De 174 cooperativas hay 121 que tienen valores nulos en sus datos.

**Guardar datos para esas cooperativas filtradas para ejecutar CAMEL**

In [11]:
data_filt.to_csv("../../tablas/Datos_2022_2025_cooperativas_CACs.csv", index=False)