# Modelo CAMEL

Usar los csv generados para los indicadores de cada variable y concatenarlos en una misma tabla de registros

In [11]:
import pandas as pd

capital = pd.read_csv("../../tablas/camel/Capital.csv")
assets = pd.read_csv("../../tablas/camel/Assets.csv")
managerial = pd.read_csv("../../tablas/camel/Managerial.csv")
earnings = pd.read_csv("../../tablas/camel/Earnings.csv")
liquidity = pd.read_csv("../../tablas/camel/Liquidity.csv")

registros_camel = pd.concat([capital, assets, managerial, earnings, liquidity], ignore_index=True)
registros_camel.head(4)

,Año,Mes,índice CAMEL,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Quebranto Patrimonial,1.408555,1.406438,1.168740,1.134147,1.756013,1.410875,1.355440,...,1.202080,1.232515,1.398206,1.835644,1.758214,1.469121,1.601338,1.139017,2.564944,1.782425
1,2021,1,Relación Solvencia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2021,1,Relación entre Aportes sociales mínimos no red...,0.895748,0.915331,0.761172,0.215563,0.751721,0.666482,0.651776,...,0.585939,0.197089,0.884482,0.545074,0.894829,0.760413,0.409011,0.699999,0.463306,0.128358
3,2021,1,Relación entre el Capital Institucional y el A...,0.088234,0.079618,0.024763,0.045663,0.088640,0.044706,0.044624,...,0.010242,0.039672,0.076342,0.092791,0.115116,0.095580,0.183472,0.035557,0.180247,0.203313

Ajustar la estructura de la tabla (mejor)

In [12]:
# Convertir de formato ancho a largo
registros_camel_long = registros_camel.melt(
    id_vars=['Año', 'Mes', 'índice CAMEL'],
    var_name='ID_cooperativa',
    value_name='valor'
)

# Renombrar columnas
registros_camel_long = registros_camel_long.rename(columns={
    'Año': 'ano',
    'Mes': 'mes',
    'índice CAMEL': 'ID_indicador'
})

# Crear ID_registro
registros_camel_long.insert(
    0,
    'ID_registro',
    range(1, len(registros_camel_long) + 1)
)

registros_camel_long.head()

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,1.408555
1,2,2021,1,Relación Solvencia,CAJA COOPERATIVA CREDICOOP,0.000000
2,3,2021,1,Relación entre Aportes sociales mínimos no red...,CAJA COOPERATIVA CREDICOOP,0.895748
3,4,2021,1,Relación entre el Capital Institucional y el A...,CAJA COOPERATIVA CREDICOOP,0.088234
4,5,2021,2,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,1.410959

In [13]:
registros_camel_long.to_csv("../../tablas/camel/Registros_CAMEL.csv", index=False, encoding="utf-8")

# Test: Modelo CAMEL sin el indicador de Solvencia

**Esta tabla contiene el indicador de Riesgo de Liquidez correspondiente a la Relación entre Activos Líquidos ampliados a depósitos de corto plazo**

In [14]:
camel_sin_solvencia = registros_camel_long.query("`ID_indicador` != 'Relación Solvencia'")
camel_sin_solvencia['ID_indicador'].unique()

<StringArray>
[                                                                 'Quebranto Patrimonial',
                 'Relación entre Aportes sociales mínimos no reducibles y Capital Social',
                              'Relación entre el Capital Institucional y el Activo Total',
                                   'Indicador de Cobertura de la Cartera Total en Riesgo',
                                                        'Indicador de calidad por riesgo',
                                           'Indicador de calidad por riesgo con castigos',
                                                                      'Activo Productivo',
 'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo',
                                                                  'Estructura de Balance',
                                            'Indicador de Margen Financiero de Operación',
                                                        'Indicador de Margen Operacional',
             'Indicador de relación entre las obligaciones financieras y el pasivo total',
                                                               'Indicador de margen neto',
                            'Indicador de rentabilidad sobre el capital invertido - ROIC',
                                 'Indicador de rentabilidad sobre recursos propios - ROE',
                                   'Activos líquidos ampliados / depósitos a corto plazo']
Length: 16, dtype: str

In [15]:
camel_sin_solvencia.to_csv("../../tablas/camel/Registros_CAMEL_sin_solvencia.csv", index=False, encoding="utf-8")

In [ ]:
camel_sin_solvencia["ID_indicador"]

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,1.408555
2,3,2021,1,Relación entre Aportes sociales mínimos no red...,CAJA COOPERATIVA CREDICOOP,0.895748
3,4,2021,1,Relación entre el Capital Institucional y el A...,CAJA COOPERATIVA CREDICOOP,0.088234
4,5,2021,2,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,1.410959
6,7,2021,2,Relación entre Aportes sociales mínimos no red...,CAJA COOPERATIVA CREDICOOP,0.895640
...,...,...,...,...,...,...
140479,140480,2025,8,Activos líquidos ampliados / depósitos a corto...,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",1.628599
140480,140481,2025,9,Activos líquidos ampliados / depósitos a corto...,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",1.576431
140481,140482,2025,10,Activos líquidos ampliados / depósitos a corto...,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",1.489434
140482,140483,2025,11,Activos líquidos ampliados / depósitos a corto...,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",1.416288
140483,140484,2025,12,Activos líquidos ampliados / depósitos a corto...,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",1.662377