1. Extraer los valores para 110500, 111000, 111500 y la fecha para cada cooperativa

In [2]:
import pandas as pd
coops = pd.read_csv("../tablas/Datos_2021_2025_cooperativas.csv", encoding="utf-8")
coops

,CUENTA,NOMBRE CUENTA,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,COOPERATIVA AVP,FEBOR ENTIDAD COOPERATIVA,...,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS,COOPERATIVA DE AHORRO Y CREDITO COLANTA,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO CAJA UNION COOPERATIVA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO TAX LA FERIA,COOPERATIVA SUYA,fecha
0,100000,ACTIVO,1.453604e+11,3.387150e+11,9.879448e+10,1.064674e+10,7.021719e+10,3.751248e+10,1.365023e+10,1.725947e+11,...,2.597647e+11,3.174706e+11,1.964690e+11,1.019668e+10,7.498950e+09,8.204825e+10,7.673873e+10,3.689148e+10,6.785967e+10,2022-02-01
1,110000,EFECTIVO Y EQUIVALENTE AL EFECTIVO,1.094558e+10,1.566943e+10,1.918907e+09,1.552585e+09,4.685907e+09,1.926925e+09,2.472604e+09,9.458176e+09,...,3.586048e+10,2.764945e+10,1.904275e+10,9.197822e+08,5.507006e+08,9.982434e+09,2.782317e+09,5.564935e+09,1.106163e+10,2022-02-01
2,110500,CAJA,2.868046e+08,8.229352e+08,3.589941e+08,1.718631e+08,1.241549e+08,8.000000e+05,6.956260e+08,3.535752e+08,...,2.000000e+06,5.735745e+09,2.193096e+09,6.007630e+07,4.744467e+08,4.490329e+08,2.018711e+08,1.615997e+08,1.612913e+09,2022-02-01
3,110505,CAJA GENERAL,2.791246e+08,8.180852e+08,3.589941e+08,1.718631e+08,1.146549e+08,0.000000e+00,6.956260e+08,3.535752e+08,...,0.000000e+00,5.732195e+09,2.182646e+09,5.907630e+07,4.738467e+08,4.450329e+08,1.998711e+08,1.600997e+08,1.612913e+09,2022-02-01
4,110510,CAJA MENOR,7.680000e+06,4.850000e+06,0.000000e+00,0.000000e+00,9.500000e+06,8.000000e+05,0.000000e+00,0.000000e+00,...,2.000000e+06,3.550000e+06,1.045000e+07,1.000000e+06,6.000000e+05,4.000000e+06,2.000000e+06,1.500000e+06,0.000000e+00,2022-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135686,931500,BIENES Y VALORES RECIBIDOS EN ADMINISTRACIÓN,0.000000e+00,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+10,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2022-05-01
135687,931505,CARTERA FOGACOOP,0.000000e+00,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+10,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2022-05-01
135688,960000,ACREEDORAS POR CONTRA (DB),7.498403e+09,4.308271e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,2.233613e+10,3.804320e+10,...,4.587332e+11,3.204788e+11,1.410674e+11,1.611099e+10,6.967973e+09,1.638770e+10,7.480500e+08,0.000000e+00,1.997420e+10,2022-05-01
135689,960500,RESPONSABILIDADES CONTINGENTES POR EL CONTRARIO,7.498403e+09,4.308271e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,2.233613e+10,3.804320e+10,...,4.587332e+11,3.204788e+11,1.410674e+11,1.611099e+10,6.967973e+09,1.638770e+10,7.480500e+08,0.000000e+00,1.997420e+10,2022-05-01
135690,980000,ACREEDORAS DE CONTROL POR CONTRA (CR),2.103902e+09,2.470562e+10,0.000000e+00,0.000000e+00,1.500000e+10,3.200000e+09,0.000000e+00,1.500000e+10,...,0.000000e+00,0.000000e+00,8.902908e+06,0.000000e+00,0.000000e+00,1.000000e+10,0.000000e+00,0.000000e+00,5.098642e+09,2022-05-01

In [3]:
target = [110500, 111000, 111500]
df_filt = coops[coops["CUENTA"].isin(target)].copy()

In [4]:
columns_base = ["CUENTA", "NOMBRE CUENTA", "fecha"]
coops_ = [col for col in coops.columns if col not in columns_base]

In [5]:
df_activos_liquidos = (
    df_filt
    .groupby("fecha")[coops_]
    .sum()
    .reset_index()
)

In [6]:
df_activos_liquidos = df_activos_liquidos[
    df_activos_liquidos["fecha"] >= "2020-01-01"
]

In [7]:
df_activos_liquidos

,fecha,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,COOPERATIVA AVP,FEBOR ENTIDAD COOPERATIVA,COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA,...,COOPERATIVA DE AHORRO Y CREDITO UNION COLOMBIANA,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS,COOPERATIVA DE AHORRO Y CREDITO COLANTA,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO CAJA UNION COOPERATIVA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO TAX LA FERIA,COOPERATIVA SUYA
0,2021-01-01,3.386772e+10,6.031279e+10,1.239768e+10,6.964603e+09,4.850863e+09,5.593702e+09,3.642232e+09,2.521330e+10,4.106709e+10,...,1.095047e+10,5.136293e+10,4.849232e+10,4.261121e+10,1.830302e+09,1.137224e+09,5.422352e+09,1.878395e+09,1.617011e+10,2.262044e+10
1,2021-02-01,2.956465e+10,5.901380e+10,1.173513e+10,6.729115e+09,4.960931e+09,5.993047e+09,3.425318e+09,2.340606e+10,3.836290e+10,...,1.189991e+10,5.059129e+10,4.105936e+10,4.274861e+10,1.207118e+09,1.395995e+09,6.407383e+09,7.721612e+08,1.499825e+10,2.088382e+10
2,2021-03-01,1.990722e+10,2.935153e+10,9.476965e+09,3.489560e+09,1.970560e+09,4.509499e+09,1.855423e+09,1.162139e+10,1.904318e+10,...,5.829672e+09,3.052693e+10,2.327256e+10,3.025058e+10,9.626440e+08,8.835591e+08,2.136627e+09,1.360559e+09,7.602235e+09,1.061206e+10
3,2021-04-01,1.990515e+10,3.043550e+10,8.613827e+09,3.673153e+09,2.620442e+09,4.211126e+09,1.875783e+09,8.473936e+09,1.994527e+10,...,5.819116e+09,3.005175e+10,1.648013e+10,1.208851e+10,3.932976e+08,6.557970e+08,1.791273e+09,6.644177e+08,8.396606e+09,1.095356e+10
4,2021-05-01,9.906622e+10,1.922631e+11,2.754746e+10,2.456198e+10,1.413351e+10,2.747958e+10,1.426901e+10,6.841626e+10,1.259982e+11,...,3.452685e+10,2.103009e+11,1.315203e+11,9.014682e+10,5.173564e+09,3.112096e+09,1.337962e+10,5.459573e+09,5.081056e+10,7.335902e+10
5,2022-01-01,1.245894e+10,2.530024e+10,1.351205e+09,3.591600e+09,2.381705e+09,2.967763e+09,1.986903e+09,1.022187e+10,1.929086e+10,...,5.549551e+09,2.041477e+10,9.230658e+09,1.437540e+10,4.493140e+08,7.016588e+08,4.154802e+09,5.312561e+08,7.864294e+09,9.221056e+09
6,2022-02-01,1.929742e+10,4.816645e+10,5.142197e+09,6.906181e+09,7.943228e+09,6.797892e+09,5.326792e+09,2.188544e+10,4.450662e+10,...,1.274845e+10,5.115204e+10,3.336436e+10,5.024133e+10,1.404344e+09,1.969140e+09,7.570106e+09,2.720402e+09,1.468299e+10,1.733358e+10
7,2022-03-01,1.415928e+10,2.477863e+10,2.944470e+09,3.920687e+09,2.817140e+09,3.165974e+09,2.354863e+09,9.106184e+09,1.801374e+10,...,6.316808e+09,2.190592e+10,1.151033e+10,1.236256e+10,4.457295e+08,1.352205e+09,3.829186e+09,1.005947e+09,8.354331e+09,9.372934e+09
8,2022-04-01,1.210136e+10,2.321412e+10,1.484534e+09,3.891760e+09,2.593052e+09,3.057439e+09,2.491995e+09,1.112363e+10,1.915730e+10,...,5.982812e+09,2.034971e+10,1.734762e+10,1.163068e+10,3.559675e+08,1.487853e+09,4.110411e+09,1.548128e+09,8.116725e+09,8.917370e+09
9,2022-05-01,5.742808e+10,1.102673e+11,1.033470e+10,1.542089e+10,1.234467e+10,2.329288e+10,1.446894e+10,4.042151e+10,8.494798e+10,...,3.589648e+10,1.668354e+11,7.494768e+10,8.601455e+10,3.435764e+09,7.469101e+09,1.596352e+10,3.090744e+09,2.817944e+10,3.030166e+10
10,2023-01-01,5.160190e+09,1.678829e+10,1.200883e+09,1.608860e+09,2.215552e+09,2.176163e+09,1.631443e+09,4.328259e+09,1.288159e+10,...,1.636765e+09,1.325864e+10,1.140750e+10,1.842965e+10,4.341229e+08,5.727950e+08,1.808000e+09,9.797466e+08,3.174072e+09,4.233378e+09
11,2023-02-01,6.137376e+09,1.793963e+10,1.080462e+09,1.313502e+09,2.592085e+09,2.395177e+09,1.607612e+09,2.534971e+09,8.681482e+09,...,2.275177e+09,1.161072e+10,1.217960e+10,1.904726e+10,3.240392e+08,5.748132e+08,1.700079e+09,1.379054e+09,3.338797e+09,3.900852e+09
12,2023-03-01,9.148542e+09,6.370571e+10,5.959584e+09,5.572250e+09,6.280925e+09,6.681346e+09,3.581597e+09,1.550919e+10,3.119314e+10,...,1.218033e+10,7.682359e+10,4.646715e+10,6.728336e+10,1.586777e+09,2.482118e+09,5.811225e+09,3.116220e+09,2.229505e+10,1.445097e+10
13,2023-04-01,5.412115e+09,2.267263e+10,3.258742e+09,1.293339e+09,1.291793e+09,3.045455e+09,9.721243e+08,2.625570e+09,1.727518e+10,...,2.038075e+09,2.810606e+10,1.158623e+10,2.096714e+10,6.420712e+08,7.682885e+08,1.585860e+09,1.870425e+09,6.001867e+09,5.390172e+09
14,2023-05-01,3.543357e+10,1.454622e+11,1.171972e+10,9.076769e+09,1.696319e+10,1.064361e+10,6.914342e+09,2.218937e+10,9.535262e+10,...,1.553862e+10,2.066530e+11,7.453126e+10,1.380161e+11,2.947638e+09,5.507118e+09,9.858924e+09,9.820389e+09,4.976090e+10,4.150005e+10
15,2024-01-01,3.071209e+09,2.905285e+10,1.067324e+09,2.397894e+09,4.574490e+09,2.532746e+09,1.091653e+09,8.834852e+09,9.274349e+09,...,5.472052e+09,2.636924e+10,1.241790e+10,2.775350e+10,2.823985e+08,5.365772e+08,2.141278e+09,9.222349e+08,1.057296e+10,6.011897e+09
16,2024-02-01,4.153555e+09,3.442172e+10,1.231914e+09,2.232904e+09,3.786415e+09,2.548488e+09,8.454383e+08,6.443999e+09,9.481203e+09,...,6.438102e+09,3.709578e+10,1.410234e+10,2.922677e+10,4.501653e+08,9.217091e+08,1.510385e+09,4.270410e+08,1.042067e+10,5.410973e+09
17,2024-03-01,5.405387e+09,3.992307e+10,2.401920e+09,2.518255e+09,3.927919e+09,2.045623e+09,1.002182e+09,6.438669e+09,9.415419e+09,...,7.397630e+09,4.175617e+10,1.310126e+10,2.721295e+10,5.546898e+08,1.082591e+09,1.152985e+09,2.851465e+08,1.044123e+10,6.490266e+09
18,2024-04-01,6.925253e+09,4.070816e+10,3.355510e+09,2.757669e+09,4.754324e+09,2.515191e+09,9.406349e+08,4.011035e+09,9.665928e+09,...,6.834646e+09,3.467787e+10,1.458646e+10,2.889339e+10,6.900098e+08,1.075433e+09,1.225697e+09,2.239254e+09,9.784469e+09,7.514703e+09
19,2024-05-01,9.301417e+10,3.232309e+11,2.018113e+10,2.294591e+10,4.734003e+10,1.861643e+10,8.555807e+09,3.867193e+10,8.374461e+10,...,5.228056e+10,2.685845e+11,1.444159e+11,2.047880e+11,4.426800e+09,1.308425e+10,1.190793e+10,1.154648e+10,7.453667e+10,6.600027e+10
20,2025-01-01,2.924653e+10,7.235195e+10,4.926194e+09,7.436488e+09,1.168814e+10,6.326625e+09,2.302999e+09,1.920733e+10,2.752880e+10,...,1.940693e+10,4.465211e+10,5.962997e+10,7.558888e+10,1.014143e+09,2.050140e+09,2.907772e+09,3.637991e+09,1.815592e+10,1.648402e+10
21,2025-02-01,1.674516e+10,4.741364e+10,2.010576e+09,3.785180e+09,6.746342e+09,2.037463e+09,9.705312e+08,6.629617e+09,8.142806e+09,...,9.852202e+09,2.893147e+10,2.423317e+10,3.532727e+10,6.682377e+08,1.526686e+09,4.668901e+09,6.954364e+08,9.292562e+09,9.198589e+09
22,2025-03-01,2.568761e+10,6.359567e+10,5.912827e+09,7.768821e+09,1.039302e+10,4.688575e+09,2.440731e+09,1.893497e+10,2.763632e+10,...,2.088597e+10,4.980541e+10,4.027991e+10,7.908616e+10,8.718633e+08,2.177412e+09,4.335547e+09,3.803166e+09,1.649690e+10,1.746901e+10
23,2025-04-01,1.455218e+10,4.948193e+10,2.208892e+09,3.702137e+09,4.501785e+09,1.823142e+09,1.079034e+09,6.715069e+09,1.149270e+10,...,9.883447e+09,3.900275e+10,1.843468e+10,4.031804e+10,1.026801e+09,1.725601e+09,1.839049e+09,2.106510e+09,9.543208e+09,1.062354e+10
24,2025-05-01,8.009720e+10,2.539769e+11,1.350316e+10,2.416620e+10,3.460179e+10,1.752773e+10,8.208052e+09,6.239277e+10,9.109740e+10,...,6.179556e+10,1.791405e+11,1.485890e+11,2.354532e+11,2.687072e+09,6.792007e+09,1.147052e+10,1.339976e+10,5.310672e+10,5.316412e+10
25,2026-01-01,1.492750e+10,1.288131e+10,2.474550e+09,3.910857e+09,4.236795e+09,2.952216e+09,1.301491e+09,9.782522e+09,2.077105e+10,...,1.113714e+10,2.696033e+10,3.130814e+10,4.368669e+10,3.406997e+08,7.290227e+08,2.123261e+09,3.689469e+09,8.369337e+09,8.955131e+09
26,2026-02-01,1.457743e+10,1.120137e+10,2.633692e+09,4.018552e+09,4.132663e+09,2.563134e+09,1.867675e+09,8.835474e+09,1.908419e+10,...,1.158588e+10,3.613751e+10,2.599742e+10,4.487314e+10,3.087389e+08,9.244221e+08,2.545721e+09,6.412703e+09,9.463331e+09,9.477615e+09
27,2026-03-01,1.491694e+10,1.264073e+10,4.025179e+09,3.984928e+09,3.738456e+09,3.343247e+09,2.309149e+09,1.065998e+10,1.901741e+10,...,9.095788e+09,3.758494e+10,2.811843e+10,4.447008e+10,2.392637e+08,1.022171e+09,2.913213e+09,2.195814e+09,9.290307e+09,1.033762e+10

In [8]:
df_activos_liquidos.to_excel("activos_liquidos_coops.xlsx", index=False)

2. Extraer histórico del IRL

In [9]:
irl_banks = pd.read_excel("../tablas/Histórico_IRL - copia.xlsx")
irl_banks

,Fecha,Tipo y código de entidad,Nombre Entidad,ALM PromedioMes,RLN PromedioMes,IRL
0,2020-03-31,1-1,Banco de Bogotá,1.378050e+10,9.218121e+09,1.495
1,2020-03-31,1-12,Banco GNB Sudameris,7.452656e+09,3.072263e+09,2.426
2,2020-03-31,1-13,BBVA Colombia,1.336877e+10,5.524700e+09,2.42
3,2020-03-31,1-2,Banco Popular,3.307329e+09,2.078626e+09,1.591
4,2020-03-31,1-23,Banco de Occidente,6.776300e+09,2.924886e+09,2.317
...,...,...,...,...,...,...
1436,2022-12-31,32-1,Cooperativa Financiera de Antioquia,9.813516e+07,4.652527e+07,2.109287
1437,2022-12-31,32-2,JFK Cooperativa Financiera,1.701561e+08,5.743336e+07,2.96267
1438,2022-12-31,32-3,Coofinep,5.994189e+07,4.029505e+07,1.487575
1439,2022-12-31,32-4,Cotrafa,1.461325e+08,7.876196e+07,1.85537
1440,2022-12-31,32-5,Confiar,1.799653e+08,1.235760e+08,1.456313

In [11]:
df_activos_liquidos["fecha"] = pd.to_datetime(df_activos_liquidos["fecha"])
irl_banks["Fecha"] = pd.to_datetime(irl_banks["Fecha"])

df_activos_liquidos["fecha_mes"] = df_activos_liquidos["fecha"].dt.to_period("M")
irl_banks["fecha_mes"] = irl_banks["Fecha"].dt.to_period("M")

In [12]:
fechas_comunes = set(df_activos_liquidos["fecha_mes"]) & set(irl_banks["fecha_mes"])

In [13]:
print(fechas_comunes)

{Period('2022-04', 'M'), Period('2021-02', 'M'), Period('2021-03', 'M'), Period('2022-02', 'M'), Period('2021-04', 'M'), Period('2022-03', 'M'), Period('2022-01', 'M'), Period('2021-05', 'M'), Period('2022-05', 'M'), Period('2021-01', 'M')}

In [14]:
df_coop = df_activos_liquidos[
    df_activos_liquidos["fecha_mes"].isin(fechas_comunes)
].sort_values("fecha_mes")

df_bancos = irl_banks[
    irl_banks["fecha_mes"].isin(fechas_comunes)
].sort_values("fecha_mes")

In [15]:
import numpy as np
import pandas as pd

# Filtrar desde marzo 2020
df_coop = df_coop[df_coop["fecha_mes"] >= "2020-03"]
df_bancos = df_bancos[df_bancos["fecha_mes"] >= "2020-03"]

# columnas cooperativas
cols_excluir = ["fecha", "fecha_mes"]
coop_nombres = [col for col in df_coop.columns if col not in cols_excluir]

# asegurar numéricos
df_coop[coop_nombres] = df_coop[coop_nombres].apply(pd.to_numeric, errors="coerce")
df_bancos["ALM PromedioMes"] = pd.to_numeric(df_bancos["ALM PromedioMes"], errors="coerce")

resultados = []

# iterar por fecha
for fecha in df_coop["fecha_mes"].unique():

    df_coop_mes = df_coop[df_coop["fecha_mes"] == fecha]
    df_bancos_mes = df_bancos[df_bancos["fecha_mes"] == fecha]

    # valores de bancos en ese mes
    bancos_mes = df_bancos_mes[["Nombre Entidad", "ALM PromedioMes"]].dropna()

    for coop in coop_nombres:
        valor_coop = df_coop_mes[coop].values[0]

        if np.isnan(valor_coop):
            continue

        mejor_banco = None
        mejor_distancia = np.inf
        mejor_valor_banco = None

        # comparar contra TODOS los bancos de ese mes
        for _, row in bancos_mes.iterrows():
            banco = row["Nombre Entidad"]
            valor_banco = row["ALM PromedioMes"]

            distancia = abs(valor_coop - valor_banco)

            if distancia < mejor_distancia:
                mejor_distancia = distancia
                mejor_banco = banco
                mejor_valor_banco = valor_banco

        resultados.append({
            "fecha_mes": fecha,
            "cooperativa": coop,
            "valor_coop": valor_coop,
            "banco_mas_parecido": mejor_banco,
            "valor_banco": mejor_valor_banco,
            "distancia": mejor_distancia
        })

df_matching = pd.DataFrame(resultados)

In [16]:
df_matching

,fecha_mes,cooperativa,valor_coop,banco_mas_parecido,valor_banco,distancia
0,2021-01,COOPERATIVA DE EMPLEADOS DE CAFAM,3.386772e+10,Bancolombia,2.233498e+10,1.153274e+10
1,2021-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,6.031279e+10,Bancolombia,2.233498e+10,3.797780e+10
2,2021-01,COOPERATIVA PARA EL BIENESTAR SOCIAL,1.239768e+10,Banco Davivienda,1.205486e+10,3.428234e+08
3,2021-01,COOPERATIVA FINANCIERA SAN FRANCISCO,6.964603e+09,Citibank,7.171877e+09,2.072738e+08
4,2021-01,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL C...,4.850863e+09,Itaú,4.759734e+09,9.112814e+07
...,...,...,...,...,...,...
1395,2022-05,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,7.469101e+09,Banagrario,6.240756e+09,1.228345e+09
1396,2022-05,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO C...,1.596352e+10,Banco Davivienda,1.368711e+10,2.276414e+09
1397,2022-05,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,3.090744e+09,Banco Caja Social S.A.,2.638573e+09,4.521711e+08
1398,2022-05,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2.817944e+10,Bancolombia,2.226085e+10,5.918592e+09
1399,2022-05,COOPERATIVA SUYA,3.030166e+10,Bancolombia,2.226085e+10,8.040808e+09

In [18]:
df_resultado = pd.merge(
    df_matching,
    irl_banks[["fecha_mes", "Nombre Entidad", "IRL"]],
    left_on=["fecha_mes", "banco_mas_parecido"],
    right_on=["fecha_mes", "Nombre Entidad"],
    how="left"
)

In [19]:
df_resultado

,fecha_mes,cooperativa,valor_coop,banco_mas_parecido,valor_banco,distancia,Nombre Entidad,IRL
0,2021-01,COOPERATIVA DE EMPLEADOS DE CAFAM,3.386772e+10,Bancolombia,2.233498e+10,1.153274e+10,Bancolombia,1.999
1,2021-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,6.031279e+10,Bancolombia,2.233498e+10,3.797780e+10,Bancolombia,1.999
2,2021-01,COOPERATIVA PARA EL BIENESTAR SOCIAL,1.239768e+10,Banco Davivienda,1.205486e+10,3.428234e+08,Banco Davivienda,1.732
3,2021-01,COOPERATIVA FINANCIERA SAN FRANCISCO,6.964603e+09,Citibank,7.171877e+09,2.072738e+08,Citibank,6.864
4,2021-01,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL C...,4.850863e+09,Itaú,4.759734e+09,9.112814e+07,Itaú,3.039
...,...,...,...,...,...,...,...,...
1395,2022-05,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,7.469101e+09,Banagrario,6.240756e+09,1.228345e+09,Banagrario,3.289024
1396,2022-05,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO C...,1.596352e+10,Banco Davivienda,1.368711e+10,2.276414e+09,Banco Davivienda,1.642897
1397,2022-05,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,3.090744e+09,Banco Caja Social S.A.,2.638573e+09,4.521711e+08,Banco Caja Social S.A.,2.766351
1398,2022-05,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2.817944e+10,Bancolombia,2.226085e+10,5.918592e+09,Bancolombia,2.092824
1399,2022-05,COOPERATIVA SUYA,3.030166e+10,Bancolombia,2.226085e+10,8.040808e+09,Bancolombia,2.092824

In [20]:
df_resultado.to_excel("../tablas/df_matching_coop_bancos_IRL.xlsx", index=False)