In [1]:
import pandas as pd

In [3]:
df_coperativas = pd.read_csv("../../tablas/camel/Registros_CAMEL.csv")
df_coperativas

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.273373
1,2,2021,1,Relación Solvencia,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.000000
2,3,2021,1,Relación entre Aportes sociales mínimos no red...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.403900
3,4,2021,1,Relación entre el Capital Institucional y el A...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.069203
4,5,2021,2,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.267651
...,...,...,...,...,...,...
121095,121096,2025,8,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",0.000000
121096,121097,2025,9,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",0.000000
121097,121098,2025,10,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",0.000000
121098,121099,2025,11,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",0.000000
121099,121100,2025,12,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",0.000000

In [5]:
df_irl = pd.read_excel("../../tablas/df_matching_coop_bancos_IRL.xlsx")
df_irl

,fecha_mes,cooperativa,valor_coop,banco_mas_parecido,valor_banco,distancia,Nombre Entidad,IRL
0,2021-01,COOPERATIVA DE EMPLEADOS DE CAFAM,3.386772e+10,Bancolombia,2.233498e+10,1.153274e+10,Bancolombia,1.999
1,2021-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,6.031279e+10,Bancolombia,2.233498e+10,3.797780e+10,Bancolombia,1.999
2,2021-01,COOPERATIVA PARA EL BIENESTAR SOCIAL,1.239768e+10,Banco Davivienda,1.205486e+10,3.428234e+08,Banco Davivienda,1.732
3,2021-01,COOPERATIVA FINANCIERA SAN FRANCISCO,6.964603e+09,Citibank,7.171877e+09,2.072738e+08,Citibank,6.864
4,2021-01,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL C...,4.850863e+09,Itaú,4.759734e+09,9.112814e+07,Itaú,3.039
...,...,...,...,...,...,...,...,...
1395,2022-05,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,7.469101e+09,Banagrario,6.240756e+09,1.228345e+09,Banagrario,3.289024
1396,2022-05,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO C...,1.596352e+10,Banco Davivienda,1.368711e+10,2.276414e+09,Banco Davivienda,1.642897
1397,2022-05,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,3.090744e+09,Banco Caja Social S.A.,2.638573e+09,4.521711e+08,Banco Caja Social S.A.,2.766351
1398,2022-05,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2.817944e+10,Bancolombia,2.226085e+10,5.918592e+09,Bancolombia,2.092824
1399,2022-05,COOPERATIVA SUYA,3.030166e+10,Bancolombia,2.226085e+10,8.040808e+09,Bancolombia,2.092824

In [6]:
df_irl["fecha_mes"] = df_irl["fecha_mes"].astype(str)

df_irl["ano"] = df_irl["fecha_mes"].str[:4].astype(int)
df_irl["mes"] = df_irl["fecha_mes"].str[5:7].astype(int)

In [7]:
df_coop_irl = df_coperativas[
    df_coperativas["ID_indicador"] == "Indicador de Riesgo de Liquidez - IRL"
].copy()

In [8]:
df_merge = pd.merge(
    df_coop_irl,
    df_irl[["cooperativa", "ano", "mes", "IRL"]],
    left_on=["ID_cooperativa", "ano", "mes"],
    right_on=["cooperativa", "ano", "mes"],
    how="inner"   
)

In [9]:
df_merge = df_merge.drop(["cooperativa", "valor"], axis=1)

In [10]:
df_merge = df_merge.rename(columns={"IRL": "valor"})

In [11]:
df_merge

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,806,2021,1,Indicador de Riesgo de Liquidez - IRL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,6.864
1,807,2021,2,Indicador de Riesgo de Liquidez - IRL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.889
2,808,2021,3,Indicador de Riesgo de Liquidez - IRL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,2.046
3,809,2021,4,Indicador de Riesgo de Liquidez - IRL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,2.698
4,810,2021,5,Indicador de Riesgo de Liquidez - IRL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.696867
...,...,...,...,...,...,...
1395,121053,2022,1,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",6.417189
1396,121054,2022,2,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.0642
1397,121055,2022,3,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.175414
1398,121056,2022,4,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.742447
1399,121057,2022,5,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.092824

Concatenar tablas

In [12]:
df_total = pd.concat([df_coperativas, df_merge], ignore_index=True)

In [13]:
df_total = df_total.drop_duplicates(
    subset=["ano", "mes", "ID_indicador", "ID_cooperativa"],
    keep="last"
)

In [14]:
df_total

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.273373
1,2,2021,1,Relación Solvencia,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.0
2,3,2021,1,Relación entre Aportes sociales mínimos no red...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.4039
3,4,2021,1,Relación entre el Capital Institucional y el A...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.069203
4,5,2021,2,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.267651
...,...,...,...,...,...,...
122495,121053,2022,1,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",6.417189
122496,121054,2022,2,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.0642
122497,121055,2022,3,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.175414
122498,121056,2022,4,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.742447
122499,121057,2022,5,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2.092824

In [16]:
df_total.to_excel("../../tablas/camel/Registros_CAMEL_con_IRL.xlsx", index=False)