# Implementación PCA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Registros de la BD

In [2]:
import pymysql

Connection successful!

### Elaborar tabla con los respectivos nombres de indicadores

In [4]:
indicadores = pd.read_sql("SELECT * FROM indicador", conn)
id_indicador = indicadores["ID_indicador"].tolist()
nombre_indicador = indicadores["nombre"].tolist()
dict_indicadores = dict(zip(id_indicador, nombre_indicador))
print(dict_indicadores)

/tmp/ipykernel_16644/3216715992.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  indicadores = pd.read_sql("SELECT * FROM indicador", conn)

{1: 'Quebranto Patrimonial', 3: 'Relación entre Aportes sociales mínimos no reducibles y Capital Social', 4: 'Relación entre el Capital Institucional y el Activo Total', 2: 'Relación Solvencia', 8: 'Activo Productivo', 6: 'Indicador de calidad por riesgo', 7: 'Indicador de calidad por riesgo con castigos', 5: 'Indicador de Cobertura de la Cartera Total en Riesgo', 9: 'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo', 10: 'Estructura de Balance', 11: 'Indicador de Margen Financiero de Operación', 12: 'Indicador de Margen Operacional', 13: 'Indicador de relación entre las obligaciones financieras y el pasivo total', 14: 'Indicador de margen neto', 15: 'Indicador de rentabilidad sobre el capital invertido - ROIC', 16: 'Indicador de rentabilidad sobre recursos propios - ROE', 17: 'Indicador de Riesgo de Liquidez - IRL'}

In [5]:
cooperativas = pd.read_sql("SELECT * FROM cooperativa", conn)
id_cooperativa = cooperativas["ID_cooperativa"].tolist()
nombre_cooperativa = cooperativas["nombre"].tolist()
dict_cooperativas = dict(zip(id_cooperativa, nombre_cooperativa))
print(dict_cooperativas)

{1: 'CAJA COOPERATIVA CREDICOOP', 2: 'CAJA COOPERATIVA PETROLERA', 3: 'CASA NACIONAL DEL PROFESOR', 4: 'COOPANTEX COOPERATIVA DE AHORRO Y CREDITO', 5: 'COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.', 6: 'COOPERATIVA BELEN AHORRO Y CREDITO', 7: 'COOPERATIVA CALDENSE DEL PROFESOR', 8: 'COOPERATIVA DE AHORRO Y CREDITO BERLIN', 9: 'COOPERATIVA DE AHORRO Y CREDITO COLANTA', 10: 'COOPERATIVA DE AHORRO Y CREDITO CONGENTE', 11: 'COOPERATIVA DE AHORRO Y CREDITO COOMPARTIR', 12: 'COOPERATIVA DE AHORRO Y CREDITO COOTRAIPI', 13: 'COOPERATIVA DE AHORRO Y CREDITO COOYAMOR', 14: 'COOPERATIVA DE AHORRO Y CREDITO CREAFAM', 15: 'COOPERATIVA DE AHORRO Y CREDITO CREAR LTDA CREARCOP', 16: 'COOPERATIVA DE AHORRO Y CREDITO DE AIPE', 17: 'COOPERATIVA DE AHORRO Y CREDITO DE CHIPAQUE', 18: 'COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS', 19: 'COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA', 20: 'COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA', 21: 'COOPERATIVA DE AHORRO Y CREDITO DE TENJO', 22: 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES UNIDOS POR EL PROGRESO', 23: 'COOPERATIVA DE AHORRO Y CREDITO DEL FUTURO', 24: 'COOPERATIVA DE AHORRO Y CREDITO DEL NUCLEO FAMILIAR DE LOS TRAB.DE ECP.LTDA', 25: 'COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS', 26: 'COOPERATIVA DE AHORRO Y CREDITO LA GRANJA LTDA.', 27: 'COOPERATIVA DE AHORRO Y CREDITO LA PLAYA DE BELEN LTDA', 28: 'COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL', 29: 'COOPERATIVA DE AHORRO Y CREDITO RIACHON LTDA.', 30: 'COOPERATIVA DE AHORRO Y CREDITO SAN MIGUEL', 31: 'COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO', 32: 'COOPERATIVA DE AHORRO Y CREDITO TABACALERA Y AGROPECUARIA LTDA', 33: 'COOPERATIVA DE AHORRO Y CREDITO UNIVERSIDAD SANTO TOMAS', 34: 'COOPERATIVA DE EMPLEADOS DEL SECTOR COOPERATIVO LTDA.', 35: 'COOPERATIVA DE EMPLEADOS SURAMERICANA', 36: 'COOPERATIVA DE FOMENTO E INVERSION SOCIAL POPULAR', 37: 'COOPERATIVA DE LA UNIVERSIDAD NACIONAL DE COLOMBIA', 38: 'COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS', 39: 'COOPERATIVA DE LOS TRABAJADORES DEL INSTITUTO DE LOS SEGUROS SOCIALES', 40: 'COOPERATIVA DE MUJERES PARA LA PROMOCION INTEGRAL', 41: 'COOPERATIVA DE PROFESIONALES DE CALDAS', 42: 'COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA', 43: 'COOPERATIVA DE PROMOCION SOCIAL', 44: 'COOPERATIVA DE TRABAJADORES DE BAVARIA DIRECCION Y VENTAS LTDA', 45: 'COOPERATIVA DE TRABAJADORES DE LA EDUCACION DEL RISARALDA', 46: 'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DEPARTAMENTALES DE ANTIOQU', 47: 'COOPERATIVA DE TRABAJADORES DEL SENA', 48: 'COOPERATIVA DE TRABAJADORES DEPARTAMENTALES DE ANTIOQUIA', 49: 'COOPERATIVA DE TRABAJADORES Y PENSIONADOS DE LA E.A.A.B.', 50: 'COOPERATIVA DE TT DE EL COLOMBIANO LTDA.', 51: 'COOPERATIVA DE YARUMAL', 52: 'COOPERATIVA DEL MAGISTERIO', 53: 'COOPERATIVA DIOCESANA DEL CLERO LTDA', 54: 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA', 55: 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO DE LA ORINOQUIA', 56: 'COOPERATIVA FINANCIERA CAFETERA', 57: 'COOPERATIVA FINANCIERA SAN FRANCISCO', 58: 'COOPERATIVA FRATERNIDAD SACERDOTAL LTDA', 59: 'COOPERATIVA INTEGRAL AGROPECUARIA LA PAZ LTDA', 60: 'COOPERATIVA INTEGRAL PARA EL DESARROLLO SOCIAL Y ECONOMICO DE TEORAMA', 61: 'COOPERATIVA LA ROSA', 62: 'COOPERATIVA LATINOAMERICANA DE AHORRO Y CREDITO', 63: 'COOPERATIVA LEON XIII DE MACEO LTDA', 64: 'COOPERATIVA MEDICA DE ANTIOQUIA LTDA', 65: 'COOPERATIVA MULTIACTIVA ANTONIO JOSE JARAMILLO TOBON', 66: 'COOPERATIVA MULTIACTIVA COOMONOMEROS', 67: 'COOPERATIVA MULTIACTIVA DE EL PAUJIL CAQUETA LIMITADA', 68: 'COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA', 69: 'COOPERATIVA MULTIACTIVA DE LOS TRABAJADORES DEL ISS', 70: 'COOPERATIVA MULTIACTIVA DE PROFESIONALES DE SANTANDER LTDA', 71: 'COOPERATIVA MULTIACTIVA DEL GUAINIA', 72: 'COOPERATIVA MULTIACTIVA DEL INEM DE IBAGUE', 73: 'COOPERATIVA MULTIACTIVA EL BAGRE LTDA', 74: 'COOPERATIVA MULTIEMPRESAS', 75: 'COOPERATIVA MULTISERVICIOS BARICHARA LTDA', 76: 'COOPERATIVA NACIONAL EDUCATIVA DE AHORRO Y CREDITO', 77: 'COOPERATIVA PARA EL BIENESTAR SOCIAL', 78: 'COOPERATIVA SAN SIMON', 79: 'COOPERATIVA SAN VICENTE DE PAUL LTDA.', 80: 'COOPERATIVA TELEPOSTAL LTDA', 81: 'COOPERATIVA TEXAS LTDA', 82: 'COPERATIVA INDEPENDIENTE DE EMPLEADOS DE ANTIOQUIA', 83: 'COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA', 84: 'COPROCENVA COOPERATIVA DE AHORRO Y CREDITO', 85: 'EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.', 86: 'FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS', 87: 'GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES', 88: 'MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA'}

/tmp/ipykernel_16644/1852280459.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cooperativas = pd.read_sql("SELECT * FROM cooperativa", conn)

In [6]:
registros = pd.read_sql("SELECT * FROM registro", conn)

/tmp/ipykernel_16644/1473806713.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  registros = pd.read_sql("SELECT * FROM registro", conn)

In [7]:
registros["ID_indicador"] = registros["ID_indicador"].map(dict_indicadores)
registros["ID_cooperativa"] = registros["ID_cooperativa"].map(dict_cooperativas)
registros.head()

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2014,1,1.500449
1,2,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2014,1,1.310736
2,3,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2014,1,1.188087
3,4,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,1.588034
4,5,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,1.481415

In [8]:
registros.to_excel("registros.xlsx", index=False)

## Visualizar DataFrame de Registros

In [32]:
registros.loc[(registros["ID_indicador"]=="Indicador de Riesgo de Liquidez - IRL")&(registros["valor"]!=0)]

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
200638,200639,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA CREDICOOP,2014,1,227.86
200639,200640,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA PETROLERA,2014,1,227.86
200640,200641,Indicador de Riesgo de Liquidez - IRL,CASA NACIONAL DEL PROFESOR,2014,1,227.86
200641,200642,Indicador de Riesgo de Liquidez - IRL,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,227.86
200642,200643,Indicador de Riesgo de Liquidez - IRL,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,227.86
...,...,...,...,...,...,...
212865,212866,Indicador de Riesgo de Liquidez - IRL,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,2025,7,216.73
212866,212867,Indicador de Riesgo de Liquidez - IRL,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO ...,2025,7,216.73
212867,212868,Indicador de Riesgo de Liquidez - IRL,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,2025,7,216.73
212868,212869,Indicador de Riesgo de Liquidez - IRL,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURS...,2025,7,216.73
212869,212870,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2025,7,216.73

## Cooperativas sectorizadas

In [60]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
import pandas as pd

In [140]:
def pesos_pca_grupo_coops(
    df,
    lista_coops,
    col_nombre="ID_cooperativa",
    n_componentes=3
):
    
    # filtrar cooperativas
    df_filtrado = df[df[col_nombre].isin(lista_coops)].copy()
    
    if df_filtrado.empty:
        raise ValueError("No hay datos para las cooperativas indicadas")
    
    # LIMPIEZA 
    df_filtrado["valor"] = (
        df_filtrado["valor"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    
    df_filtrado["valor"] = pd.to_numeric(df_filtrado["valor"], errors="coerce")
    
    # pivot (matriz indicadores)
    df_pivot = df_filtrado.pivot_table(
        index=col_nombre,
        columns="ID_indicador",
        values="valor",
        aggfunc="mean"
    )
    
    # imputar faltantes
    imputer = SimpleImputer(strategy="mean")
    X_imputed = imputer.fit_transform(df_pivot)
    
    # escalar
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)
    
    # PCA
    pca = PCA(n_components=min(n_componentes, df_pivot.shape[1]))
    pca.fit(X_scaled)
    
    loadings = pd.DataFrame(
        pca.components_.T,
        index=df_pivot.columns
    )
    
    pesos = (loadings**2).mean(axis=1)
    
    # porcentaje
    pesos = (pesos / pesos.sum()) * 100
    
    return pesos.sort_values(ascending=False)

### Organizar datos para aplicar PCA

In [141]:
import pandas as pd

In [142]:
coop_categories = pd.read_excel("../tablas/registros_categorizados_con_IRL_yq_solvencia.xlsx")
coop_categories=coop_categories.loc[coop_categories["ID_indicador"]!="Indicador de Riesgo de Liquidez - IRL"]
coop_categories=coop_categories.loc[coop_categories["ano"]>=2020]
coop_categories=coop_categories.loc[coop_categories["ano"]<=2022]    
coop_categories.head()

,Unnamed: 0,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor,categoria
25344,25344,25345,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2020,1,0.0,Medianas
25345,25345,25346,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2020,1,0.0,Megas
25346,25346,25347,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2020,1,0.0,Megas
25347,25347,25348,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2020,1,0.0,Grandes
25348,25348,25349,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2020,1,0.0,Medianas

In [143]:
coop_categories["ID_indicador"].unique()

array(['Quebranto Patrimonial', 'Relación Solvencia',
       'Relación entre Aportes sociales mínimos no reducibles y Capital Social',
       'Relación entre el Capital Institucional y el Activo Total',
       'Indicador de Cobertura de la Cartera Total en Riesgo',
       'Indicador de calidad por riesgo',
       'Indicador de calidad por riesgo con castigos',
       'Activo Productivo',
       'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo',
       'Estructura de Balance',
       'Indicador de Margen Financiero de Operación',
       'Indicador de Margen Operacional',
       'Indicador de relación entre las obligaciones financieras y el pasivo total',
       'Indicador de margen neto',
       'Indicador de rentabilidad sobre el capital invertido - ROIC',
       'Indicador de rentabilidad sobre recursos propios - ROE'],
      dtype=object)

In [144]:
names_coop = coop_categories["ID_cooperativa"].tolist()
pesos_pca_grupo_coops(df=coop_categories, lista_coops=names_coop)

ID_indicador
Quebranto Patrimonial                                                                     11.143130
Indicador de Margen Financiero de Operación                                               10.861445
Indicador de rentabilidad sobre recursos propios - ROE                                    10.695625
Estructura de Balance                                                                      9.915876
Relación entre el Capital Institucional y el Activo Total                                  8.234379
Indicador de Cobertura de la Cartera Total en Riesgo                                       8.224070
Indicador de rentabilidad sobre el capital invertido - ROIC                                7.176308
Indicador de margen neto                                                                   6.647010
Indicador de Margen Operacional                                                            6.360340
Indicador de calidad por riesgo                                                            6.351212
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     6.191543
Indicador de calidad por riesgo con castigos                                               2.706747
Activo Productivo                                                                          1.674371
Indicador de relación entre las obligaciones financieras y el pasivo total                 1.448019
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     1.330375
Relación Solvencia                                                                         1.039549
dtype: float64

---

In [145]:
coop_categories["categoria"].unique()

array(['Medianas', 'Megas', 'Grandes', 'Micro 2', 'Pequeñas', 'Micro 1',
       'Top 4'], dtype=object)

In [146]:
coop_categories.loc[coop_categories["categoria"]=="Top 4","categoria"]="Megas"

In [147]:
def data_categorias(coop_categories, categoria):
    names_coop = coop_categories[coop_categories["categoria"]==categoria]["ID_cooperativa"].tolist()
    df_category = coop_categories[coop_categories["ID_cooperativa"].isin(names_coop)]

    return df_category, names_coop

Megas

In [148]:
df_megas, megas_coops = data_categorias(coop_categories, "Megas")
pesos_pca_grupo_coops(df=df_megas, lista_coops=megas_coops)

ID_indicador
Quebranto Patrimonial                                                                     8.060420
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    7.929358
Indicador de rentabilidad sobre recursos propios - ROE                                    7.753688
Indicador de relación entre las obligaciones financieras y el pasivo total                7.251470
Indicador de rentabilidad sobre el capital invertido - ROIC                               7.179555
Indicador de margen neto                                                                  7.086649
Estructura de Balance                                                                     6.718343
Relación entre el Capital Institucional y el Activo Total                                 6.437077
Indicador de calidad por riesgo con castigos                                              6.353816
Indicador de Margen Financiero de Operación                                               6.335289
Indicador de Cobertura de la Cartera Total en Riesgo                                      6.333847
Indicador de calidad por riesgo                                                           6.290801
Indicador de Margen Operacional                                                           6.175572
Relación Solvencia                                                                        4.867414
Activo Productivo                                                                         2.675294
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    2.551406
dtype: float64

Grandes

In [149]:
df_grandes, grandes_coops = data_categorias(coop_categories, "Grandes")
pesos_pca_grupo_coops(df=df_grandes, lista_coops=grandes_coops)

ID_indicador
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    10.399673
Indicador de relación entre las obligaciones financieras y el pasivo total                 9.897419
Quebranto Patrimonial                                                                      8.509886
Activo Productivo                                                                          7.882423
Estructura de Balance                                                                      7.709548
Relación entre el Capital Institucional y el Activo Total                                  6.830143
Relación Solvencia                                                                         6.794936
Indicador de Margen Financiero de Operación                                                6.615378
Indicador de Margen Operacional                                                            6.100526
Indicador de rentabilidad sobre recursos propios - ROE                                     5.640985
Indicador de margen neto                                                                   4.970467
Indicador de rentabilidad sobre el capital invertido - ROIC                                4.831829
Indicador de calidad por riesgo                                                            3.979469
Indicador de calidad por riesgo con castigos                                               3.879112
Indicador de Cobertura de la Cartera Total en Riesgo                                       3.473210
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     2.484996
dtype: float64

Medianas

In [150]:
df_medianas, medianas_coops = data_categorias(coop_categories, "Medianas")
pesos_pca_grupo_coops(df=df_medianas, lista_coops=medianas_coops)

ID_indicador
Quebranto Patrimonial                                                                     9.397720
Estructura de Balance                                                                     9.190017
Indicador de rentabilidad sobre recursos propios - ROE                                    9.148404
Indicador de Margen Financiero de Operación                                               8.709264
Relación entre el Capital Institucional y el Activo Total                                 8.403352
Indicador de Cobertura de la Cartera Total en Riesgo                                      8.218287
Indicador de calidad por riesgo                                                           7.410931
Indicador de rentabilidad sobre el capital invertido - ROIC                               6.435383
Indicador de margen neto                                                                  6.245725
Indicador de Margen Operacional                                                           5.903060
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    5.027024
Indicador de calidad por riesgo con castigos                                              4.126346
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    4.067414
Indicador de relación entre las obligaciones financieras y el pasivo total                3.961007
Relación Solvencia                                                                        1.963151
Activo Productivo                                                                         1.792916
dtype: float64

Pequeñas

In [151]:
df_pequeñas, pequeñas_coops = data_categorias(coop_categories, "Pequeñas")
pesos_pca_grupo_coops(df=df_pequeñas, lista_coops=pequeñas_coops)

ID_indicador
Estructura de Balance                                                                     8.925726
Indicador de margen neto                                                                  8.676414
Indicador de rentabilidad sobre recursos propios - ROE                                    8.383781
Indicador de rentabilidad sobre el capital invertido - ROIC                               8.160328
Indicador de Cobertura de la Cartera Total en Riesgo                                      7.372236
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    7.365392
Activo Productivo                                                                         7.179134
Relación Solvencia                                                                        6.776015
Indicador de calidad por riesgo                                                           6.644776
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    6.365438
Indicador de Margen Operacional                                                           5.423243
Indicador de relación entre las obligaciones financieras y el pasivo total                5.304523
Indicador de calidad por riesgo con castigos                                              4.347081
Quebranto Patrimonial                                                                     4.255756
Relación entre el Capital Institucional y el Activo Total                                 3.635321
Indicador de Margen Financiero de Operación                                               1.184837
dtype: float64

Micro 1

In [152]:
df_micro1, micro1_coops = data_categorias(coop_categories, "Micro 1")
pesos_pca_grupo_coops(df=df_micro1, lista_coops=micro1_coops)

ID_indicador
Indicador de Cobertura de la Cartera Total en Riesgo                                      11.028763
Indicador de rentabilidad sobre recursos propios - ROE                                     9.779364
Quebranto Patrimonial                                                                      9.636287
Indicador de relación entre las obligaciones financieras y el pasivo total                 8.520404
Activo Productivo                                                                          7.845226
Indicador de rentabilidad sobre el capital invertido - ROIC                                7.702714
Relación entre el Capital Institucional y el Activo Total                                  7.066775
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     5.861207
Indicador de margen neto                                                                   5.428910
Estructura de Balance                                                                      5.353109
Indicador de Margen Operacional                                                            5.273565
Indicador de calidad por riesgo con castigos                                               4.281661
Indicador de Margen Financiero de Operación                                                4.034432
Indicador de calidad por riesgo                                                            3.463770
Relación Solvencia                                                                         2.780979
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     1.942835
dtype: float64

Micro 2

In [153]:
df_micro2, micro2_coops = data_categorias(coop_categories, "Micro 2")
pesos_pca_grupo_coops(df=df_micro2, lista_coops=micro2_coops)

ID_indicador
Indicador de Margen Financiero de Operación                                               11.968577
Relación entre el Capital Institucional y el Activo Total                                 10.761238
Quebranto Patrimonial                                                                     10.086003
Estructura de Balance                                                                      8.233937
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     7.628532
Indicador de rentabilidad sobre el capital invertido - ROIC                                6.242511
Indicador de calidad por riesgo con castigos                                               5.853394
Indicador de margen neto                                                                   5.512912
Indicador de Margen Operacional                                                            5.170044
Indicador de Cobertura de la Cartera Total en Riesgo                                       5.116811
Indicador de relación entre las obligaciones financieras y el pasivo total                 4.972187
Activo Productivo                                                                          4.566294
Indicador de rentabilidad sobre recursos propios - ROE                                     4.395613
Indicador de calidad por riesgo                                                            3.825376
Relación Solvencia                                                                         3.571473
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     2.095099
dtype: float64