# Implementación PCA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Registros de la BD

In [2]:
import pymysql

Connection successful!

### Elaborar tabla con los respectivos nombres de indicadores

In [4]:
indicadores = pd.read_sql("SELECT * FROM indicador", conn)
id_indicador = indicadores["ID_indicador"].tolist()
nombre_indicador = indicadores["nombre"].tolist()
dict_indicadores = dict(zip(id_indicador, nombre_indicador))
print(dict_indicadores)

/tmp/ipykernel_16644/3216715992.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  indicadores = pd.read_sql("SELECT * FROM indicador", conn)

{1: 'Quebranto Patrimonial', 3: 'Relación entre Aportes sociales mínimos no reducibles y Capital Social', 4: 'Relación entre el Capital Institucional y el Activo Total', 2: 'Relación Solvencia', 8: 'Activo Productivo', 6: 'Indicador de calidad por riesgo', 7: 'Indicador de calidad por riesgo con castigos', 5: 'Indicador de Cobertura de la Cartera Total en Riesgo', 9: 'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo', 10: 'Estructura de Balance', 11: 'Indicador de Margen Financiero de Operación', 12: 'Indicador de Margen Operacional', 13: 'Indicador de relación entre las obligaciones financieras y el pasivo total', 14: 'Indicador de margen neto', 15: 'Indicador de rentabilidad sobre el capital invertido - ROIC', 16: 'Indicador de rentabilidad sobre recursos propios - ROE', 17: 'Indicador de Riesgo de Liquidez - IRL'}

In [5]:
cooperativas = pd.read_sql("SELECT * FROM cooperativa", conn)
id_cooperativa = cooperativas["ID_cooperativa"].tolist()
nombre_cooperativa = cooperativas["nombre"].tolist()
dict_cooperativas = dict(zip(id_cooperativa, nombre_cooperativa))
print(dict_cooperativas)

{1: 'CAJA COOPERATIVA CREDICOOP', 2: 'CAJA COOPERATIVA PETROLERA', 3: 'CASA NACIONAL DEL PROFESOR', 4: 'COOPANTEX COOPERATIVA DE AHORRO Y CREDITO', 5: 'COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.', 6: 'COOPERATIVA BELEN AHORRO Y CREDITO', 7: 'COOPERATIVA CALDENSE DEL PROFESOR', 8: 'COOPERATIVA DE AHORRO Y CREDITO BERLIN', 9: 'COOPERATIVA DE AHORRO Y CREDITO COLANTA', 10: 'COOPERATIVA DE AHORRO Y CREDITO CONGENTE', 11: 'COOPERATIVA DE AHORRO Y CREDITO COOMPARTIR', 12: 'COOPERATIVA DE AHORRO Y CREDITO COOTRAIPI', 13: 'COOPERATIVA DE AHORRO Y CREDITO COOYAMOR', 14: 'COOPERATIVA DE AHORRO Y CREDITO CREAFAM', 15: 'COOPERATIVA DE AHORRO Y CREDITO CREAR LTDA CREARCOP', 16: 'COOPERATIVA DE AHORRO Y CREDITO DE AIPE', 17: 'COOPERATIVA DE AHORRO Y CREDITO DE CHIPAQUE', 18: 'COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS', 19: 'COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA', 20: 'COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA', 21: 'COOPERATIVA DE AHORRO Y CREDITO DE TENJO', 22: 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES UNIDOS POR EL PROGRESO', 23: 'COOPERATIVA DE AHORRO Y CREDITO DEL FUTURO', 24: 'COOPERATIVA DE AHORRO Y CREDITO DEL NUCLEO FAMILIAR DE LOS TRAB.DE ECP.LTDA', 25: 'COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS', 26: 'COOPERATIVA DE AHORRO Y CREDITO LA GRANJA LTDA.', 27: 'COOPERATIVA DE AHORRO Y CREDITO LA PLAYA DE BELEN LTDA', 28: 'COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL', 29: 'COOPERATIVA DE AHORRO Y CREDITO RIACHON LTDA.', 30: 'COOPERATIVA DE AHORRO Y CREDITO SAN MIGUEL', 31: 'COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO', 32: 'COOPERATIVA DE AHORRO Y CREDITO TABACALERA Y AGROPECUARIA LTDA', 33: 'COOPERATIVA DE AHORRO Y CREDITO UNIVERSIDAD SANTO TOMAS', 34: 'COOPERATIVA DE EMPLEADOS DEL SECTOR COOPERATIVO LTDA.', 35: 'COOPERATIVA DE EMPLEADOS SURAMERICANA', 36: 'COOPERATIVA DE FOMENTO E INVERSION SOCIAL POPULAR', 37: 'COOPERATIVA DE LA UNIVERSIDAD NACIONAL DE COLOMBIA', 38: 'COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS', 39: 'COOPERATIVA DE LOS TRABAJADORES DEL INSTITUTO DE LOS SEGUROS SOCIALES', 40: 'COOPERATIVA DE MUJERES PARA LA PROMOCION INTEGRAL', 41: 'COOPERATIVA DE PROFESIONALES DE CALDAS', 42: 'COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA', 43: 'COOPERATIVA DE PROMOCION SOCIAL', 44: 'COOPERATIVA DE TRABAJADORES DE BAVARIA DIRECCION Y VENTAS LTDA', 45: 'COOPERATIVA DE TRABAJADORES DE LA EDUCACION DEL RISARALDA', 46: 'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DEPARTAMENTALES DE ANTIOQU', 47: 'COOPERATIVA DE TRABAJADORES DEL SENA', 48: 'COOPERATIVA DE TRABAJADORES DEPARTAMENTALES DE ANTIOQUIA', 49: 'COOPERATIVA DE TRABAJADORES Y PENSIONADOS DE LA E.A.A.B.', 50: 'COOPERATIVA DE TT DE EL COLOMBIANO LTDA.', 51: 'COOPERATIVA DE YARUMAL', 52: 'COOPERATIVA DEL MAGISTERIO', 53: 'COOPERATIVA DIOCESANA DEL CLERO LTDA', 54: 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA', 55: 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO DE LA ORINOQUIA', 56: 'COOPERATIVA FINANCIERA CAFETERA', 57: 'COOPERATIVA FINANCIERA SAN FRANCISCO', 58: 'COOPERATIVA FRATERNIDAD SACERDOTAL LTDA', 59: 'COOPERATIVA INTEGRAL AGROPECUARIA LA PAZ LTDA', 60: 'COOPERATIVA INTEGRAL PARA EL DESARROLLO SOCIAL Y ECONOMICO DE TEORAMA', 61: 'COOPERATIVA LA ROSA', 62: 'COOPERATIVA LATINOAMERICANA DE AHORRO Y CREDITO', 63: 'COOPERATIVA LEON XIII DE MACEO LTDA', 64: 'COOPERATIVA MEDICA DE ANTIOQUIA LTDA', 65: 'COOPERATIVA MULTIACTIVA ANTONIO JOSE JARAMILLO TOBON', 66: 'COOPERATIVA MULTIACTIVA COOMONOMEROS', 67: 'COOPERATIVA MULTIACTIVA DE EL PAUJIL CAQUETA LIMITADA', 68: 'COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA', 69: 'COOPERATIVA MULTIACTIVA DE LOS TRABAJADORES DEL ISS', 70: 'COOPERATIVA MULTIACTIVA DE PROFESIONALES DE SANTANDER LTDA', 71: 'COOPERATIVA MULTIACTIVA DEL GUAINIA', 72: 'COOPERATIVA MULTIACTIVA DEL INEM DE IBAGUE', 73: 'COOPERATIVA MULTIACTIVA EL BAGRE LTDA', 74: 'COOPERATIVA MULTIEMPRESAS', 75: 'COOPERATIVA MULTISERVICIOS BARICHARA LTDA', 76: 'COOPERATIVA NACIONAL EDUCATIVA DE AHORRO Y CREDITO', 77: 'COOPERATIVA PARA EL BIENESTAR SOCIAL', 78: 'COOPERATIVA SAN SIMON', 79: 'COOPERATIVA SAN VICENTE DE PAUL LTDA.', 80: 'COOPERATIVA TELEPOSTAL LTDA', 81: 'COOPERATIVA TEXAS LTDA', 82: 'COPERATIVA INDEPENDIENTE DE EMPLEADOS DE ANTIOQUIA', 83: 'COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA', 84: 'COPROCENVA COOPERATIVA DE AHORRO Y CREDITO', 85: 'EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.', 86: 'FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS', 87: 'GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES', 88: 'MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA'}

/tmp/ipykernel_16644/1852280459.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cooperativas = pd.read_sql("SELECT * FROM cooperativa", conn)

In [6]:
registros = pd.read_sql("SELECT * FROM registro", conn)

/tmp/ipykernel_16644/1473806713.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  registros = pd.read_sql("SELECT * FROM registro", conn)

In [7]:
registros["ID_indicador"] = registros["ID_indicador"].map(dict_indicadores)
registros["ID_cooperativa"] = registros["ID_cooperativa"].map(dict_cooperativas)
registros.head()

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2014,1,1.500449
1,2,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2014,1,1.310736
2,3,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2014,1,1.188087
3,4,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,1.588034
4,5,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,1.481415

In [8]:
registros.to_excel("registros.xlsx", index=False)

## Visualizar DataFrame de Registros

In [32]:
registros.loc[(registros["ID_indicador"]=="Indicador de Riesgo de Liquidez - IRL")&(registros["valor"]!=0)]

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
200638,200639,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA CREDICOOP,2014,1,227.86
200639,200640,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA PETROLERA,2014,1,227.86
200640,200641,Indicador de Riesgo de Liquidez - IRL,CASA NACIONAL DEL PROFESOR,2014,1,227.86
200641,200642,Indicador de Riesgo de Liquidez - IRL,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,227.86
200642,200643,Indicador de Riesgo de Liquidez - IRL,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,227.86
...,...,...,...,...,...,...
212865,212866,Indicador de Riesgo de Liquidez - IRL,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,2025,7,216.73
212866,212867,Indicador de Riesgo de Liquidez - IRL,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO ...,2025,7,216.73
212867,212868,Indicador de Riesgo de Liquidez - IRL,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,2025,7,216.73
212868,212869,Indicador de Riesgo de Liquidez - IRL,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURS...,2025,7,216.73
212869,212870,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2025,7,216.73

## Cooperativas sectorizadas

In [1]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
import pandas as pd

In [2]:
def pesos_pca_grupo_coops(
    df,
    lista_coops,
    col_nombre="ID_cooperativa",
    n_componentes=3
):
    
    # filtrar cooperativas
    df_filtrado = df[df[col_nombre].isin(lista_coops)].copy()
    
    if df_filtrado.empty:
        raise ValueError("No hay datos para las cooperativas indicadas")
    
    # LIMPIEZA 
    df_filtrado["valor"] = (
        df_filtrado["valor"]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    
    df_filtrado["valor"] = pd.to_numeric(df_filtrado["valor"], errors="coerce")
    
    # pivot (matriz indicadores)
    df_pivot = df_filtrado.pivot_table(
        index=col_nombre,
        columns="ID_indicador",
        values="valor",
        aggfunc="mean"
    )
    
    # imputar faltantes
    imputer = SimpleImputer(strategy="mean")
    X_imputed = imputer.fit_transform(df_pivot)
    
    # escalar
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)
    
    # PCA
    pca = PCA(n_components=min(n_componentes, df_pivot.shape[1]))
    pca.fit(X_scaled)
    
    loadings = pd.DataFrame(
        pca.components_.T,
        index=df_pivot.columns
    )
    
    pesos = (loadings**2).mean(axis=1)
    
    # porcentaje
    pesos = (pesos / pesos.sum()) * 100
    
    return pesos.sort_values(ascending=False)

### Organizar datos para aplicar PCA

In [3]:
import pandas as pd

In [5]:
#coop_categories = pd.read_excel("../tablas/registros_irl_para_pca.xlsx")
#coop_categories=coop_categories.loc[coop_categories["ID_indicador"]!="Indicador de Riesgo de Liquidez - IRL"]
#coop_categories=coop_categories.loc[coop_categories["ano"]>=2020]
#coop_categories=coop_categories.loc[coop_categories["ano"]<=2022]    
#coop_categories.head()
coop_categories = pd.read_excel("../tablas/registros_categorizados_con_IRL.xlsx")

In [6]:
coop_categories

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor,categoria
0,25345,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2020,1,0.000000e+00,Medianas
1,25346,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2020,1,0.000000e+00,Megas
2,25347,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2020,1,0.000000e+00,Megas
3,25348,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2020,1,0.000000e+00,Grandes
4,25349,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2020,1,0.000000e+00,Medianas
...,...,...,...,...,...,...,...
105855,99,IRL,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2025,8,7.624826e+08,Micro 2
105856,99,IRL,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2025,9,9.911326e+08,Micro 2
105857,99,IRL,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2025,10,9.842681e+08,Micro 2
105858,99,IRL,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2025,11,5.706928e+08,Micro 2
105859,99,IRL,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,2025,12,5.918078e+08,Micro 2

In [8]:
coop_categories["ID_indicador"].unique()

array(['Quebranto Patrimonial', 'Relación Solvencia',
       'Relación entre Aportes sociales mínimos no reducibles y Capital Social',
       'Relación entre el Capital Institucional y el Activo Total',
       'Indicador de Cobertura de la Cartera Total en Riesgo',
       'Indicador de calidad por riesgo',
       'Indicador de calidad por riesgo con castigos',
       'Activo Productivo',
       'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo',
       'Estructura de Balance',
       'Indicador de Margen Financiero de Operación',
       'Indicador de Margen Operacional',
       'Indicador de relación entre las obligaciones financieras y el pasivo total',
       'Indicador de margen neto',
       'Indicador de rentabilidad sobre el capital invertido - ROIC',
       'Indicador de rentabilidad sobre recursos propios - ROE', 'IRL'],
      dtype=object)

In [9]:
names_coop = coop_categories["ID_cooperativa"].tolist()
pesos_pca_grupo_coops(df=coop_categories, lista_coops=names_coop)

ID_indicador
Quebranto Patrimonial                                                                     11.267600
Indicador de Margen Financiero de Operación                                               10.464778
Estructura de Balance                                                                      9.044563
Indicador de rentabilidad sobre recursos propios - ROE                                     8.924425
Indicador de Cobertura de la Cartera Total en Riesgo                                       8.074197
Relación entre el Capital Institucional y el Activo Total                                  7.535087
Indicador de rentabilidad sobre el capital invertido - ROIC                                6.587928
Indicador de margen neto                                                                   6.248995
Indicador de calidad por riesgo                                                            6.185444
Indicador de Margen Operacional                                                            5.706752
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     5.192277
IRL                                                                                        4.428318
Indicador de calidad por riesgo con castigos                                               2.965615
Activo Productivo                                                                          2.787184
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     1.601881
Relación Solvencia                                                                         1.578824
Indicador de relación entre las obligaciones financieras y el pasivo total                 1.406129
dtype: float64

---

In [11]:
coop_categories["categoria"].unique()

array(['Medianas', 'Megas', 'Grandes', 'Micro 2', 'Pequeñas', 'Micro 1',
       'Top 4'], dtype=object)

In [12]:
coop_categories.loc[coop_categories["categoria"]=="Top 4","categoria"]="Megas"

In [13]:
def data_categorias(coop_categories, categoria):
    names_coop = coop_categories[coop_categories["categoria"]==categoria]["ID_cooperativa"].tolist()
    df_category = coop_categories[coop_categories["ID_cooperativa"].isin(names_coop)]

    return df_category, names_coop

Megas

In [14]:
df_megas, megas_coops = data_categorias(coop_categories, "Megas")
pesos_pca_grupo_coops(df=df_megas, lista_coops=megas_coops)

ID_indicador
Indicador de relación entre las obligaciones financieras y el pasivo total                8.409253
Quebranto Patrimonial                                                                     8.342567
Estructura de Balance                                                                     6.757204
Relación entre el Capital Institucional y el Activo Total                                 6.625139
Indicador de calidad por riesgo con castigos                                              6.602162
Indicador de rentabilidad sobre recursos propios - ROE                                    6.588026
Indicador de Cobertura de la Cartera Total en Riesgo                                      6.070142
Indicador de Margen Financiero de Operación                                               5.979167
Indicador de calidad por riesgo                                                           5.806637
Activo Productivo                                                                         5.652105
Indicador de rentabilidad sobre el capital invertido - ROIC                               5.500586
Indicador de margen neto                                                                  5.395330
IRL                                                                                       5.257464
Indicador de Margen Operacional                                                           4.825379
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    4.751000
Relación Solvencia                                                                        3.735643
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    3.702198
dtype: float64

Grandes

In [15]:
df_grandes, grandes_coops = data_categorias(coop_categories, "Grandes")
pesos_pca_grupo_coops(df=df_grandes, lista_coops=grandes_coops)

ID_indicador
IRL                                                                                       10.351330
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     9.217975
Estructura de Balance                                                                      7.965107
Activo Productivo                                                                          6.866733
Relación entre el Capital Institucional y el Activo Total                                  6.603372
Quebranto Patrimonial                                                                      6.379481
Indicador de Margen Financiero de Operación                                                6.143961
Indicador de relación entre las obligaciones financieras y el pasivo total                 5.924031
Indicador de calidad por riesgo                                                            5.482142
Relación Solvencia                                                                         4.875218
Indicador de margen neto                                                                   4.731154
Indicador de Margen Operacional                                                            4.700262
Indicador de rentabilidad sobre recursos propios - ROE                                     4.492167
Indicador de rentabilidad sobre el capital invertido - ROIC                                4.387142
Indicador de calidad por riesgo con castigos                                               4.335952
Indicador de Cobertura de la Cartera Total en Riesgo                                       3.866721
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     3.677252
dtype: float64

Medianas

In [16]:
df_medianas, medianas_coops = data_categorias(coop_categories, "Medianas")
pesos_pca_grupo_coops(df=df_medianas, lista_coops=medianas_coops)

ID_indicador
Quebranto Patrimonial                                                                     9.438316
Indicador de Margen Financiero de Operación                                               9.047208
Estructura de Balance                                                                     8.488860
Relación entre el Capital Institucional y el Activo Total                                 8.364811
Indicador de rentabilidad sobre recursos propios - ROE                                    8.204066
Indicador de Cobertura de la Cartera Total en Riesgo                                      7.769780
Indicador de calidad por riesgo                                                           7.216846
Indicador de rentabilidad sobre el capital invertido - ROIC                               5.816661
Indicador de margen neto                                                                  5.672465
Indicador de Margen Operacional                                                           5.451587
IRL                                                                                       5.411699
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    4.142161
Indicador de calidad por riesgo con castigos                                              3.863564
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    3.606350
Indicador de relación entre las obligaciones financieras y el pasivo total                3.560053
Relación Solvencia                                                                        2.517586
Activo Productivo                                                                         1.427987
dtype: float64

Pequeñas

In [17]:
df_pequeñas, pequeñas_coops = data_categorias(coop_categories, "Pequeñas")
pesos_pca_grupo_coops(df=df_pequeñas, lista_coops=pequeñas_coops)

ID_indicador
Estructura de Balance                                                                     8.777256
Indicador de Cobertura de la Cartera Total en Riesgo                                      8.061878
Indicador de rentabilidad sobre recursos propios - ROE                                    7.702689
Activo Productivo                                                                         7.337547
Indicador de rentabilidad sobre el capital invertido - ROIC                               7.200773
Relación entre Aportes sociales mínimos no reducibles y Capital Social                    7.021694
Indicador de margen neto                                                                  6.753412
IRL                                                                                       6.471726
Relación Solvencia                                                                        6.289854
Quebranto Patrimonial                                                                     5.781934
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    5.501866
Indicador de Margen Operacional                                                           4.927823
Indicador de calidad por riesgo                                                           4.684248
Indicador de relación entre las obligaciones financieras y el pasivo total                4.485149
Indicador de calidad por riesgo con castigos                                              4.150705
Relación entre el Capital Institucional y el Activo Total                                 3.955584
Indicador de Margen Financiero de Operación                                               0.895864
dtype: float64

Micro 1

In [18]:
df_micro1, micro1_coops = data_categorias(coop_categories, "Micro 1")
pesos_pca_grupo_coops(df=df_micro1, lista_coops=micro1_coops)

ID_indicador
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo    13.422119
Indicador de rentabilidad sobre recursos propios - ROE                                     8.268047
Indicador de Cobertura de la Cartera Total en Riesgo                                       7.766218
Estructura de Balance                                                                      7.736813
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     6.890449
Quebranto Patrimonial                                                                      6.768413
Indicador de rentabilidad sobre el capital invertido - ROIC                                6.393423
Indicador de margen neto                                                                   6.297249
IRL                                                                                        5.748476
Indicador de Margen Financiero de Operación                                                5.637762
Relación entre el Capital Institucional y el Activo Total                                  4.823569
Indicador de Margen Operacional                                                            4.707141
Indicador de calidad por riesgo                                                            4.403242
Activo Productivo                                                                          4.214618
Relación Solvencia                                                                         3.040734
Indicador de relación entre las obligaciones financieras y el pasivo total                 1.960241
Indicador de calidad por riesgo con castigos                                               1.921484
dtype: float64

Micro 2

In [19]:
df_micro2, micro2_coops = data_categorias(coop_categories, "Micro 2")
pesos_pca_grupo_coops(df=df_micro2, lista_coops=micro2_coops)

ID_indicador
Indicador de Margen Financiero de Operación                                               11.178053
Indicador de relación entre las obligaciones financieras y el pasivo total                 9.899906
IRL                                                                                        8.242402
Indicador de Cobertura de la Cartera Total en Riesgo                                       8.114038
Indicador de calidad por riesgo con castigos                                               6.836623
Indicador de rentabilidad sobre el capital invertido - ROIC                                6.355679
Indicador de margen neto                                                                   6.127960
Indicador de Margen Operacional                                                            6.117224
Estructura de Balance                                                                      6.080239
Indicador de calidad por riesgo                                                            5.380530
Activo Productivo                                                                          5.350734
Indicador de rentabilidad sobre recursos propios - ROE                                     4.757880
Relación Solvencia                                                                         4.432238
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     3.568647
Quebranto Patrimonial                                                                      2.942052
Relación entre el Capital Institucional y el Activo Total                                  2.500409
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     2.115389
dtype: float64