1. Extraer los valores para 110500, 111000, 111500 y la fecha para cada cooperativa

In [1]:
import pandas as pd
coops = pd.read_excel("Datos_2013_2025_cooperativas.xlsx")
coops

FileNotFoundError: [Errno 2] No such file or directory: 'Datos_2013_2025_cooperativas.xlsx'

In [ ]:
target = [110500, 111000, 111500]
df_filt = coops[coops["CUENTA"].isin(target)].copy()

In [ ]:
columns_base = ["CUENTA", "NOMBRE CUENTA", "fecha"]
coops_ = [col for col in coops.columns if col not in columns_base]

In [ ]:
df_activos_liquidos = (
    df_filt
    .groupby("fecha")[coops_]
    .sum()
    .reset_index()
)

In [ ]:
df_activos_liquidos = df_activos_liquidos[
    df_activos_liquidos["fecha"] >= "2020-01-01"
]

In [ ]:
df_activos_liquidos

,fecha,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA,CAJA COOPERATIVA CREDICOOP,COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,...,COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO BERLIN,COOPERATIVA DE AHORRO Y CREDITO DE AIPE,COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA,COOPERATIVA BELEN AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS,COOPERATIVA DE AHORRO Y CREDITO COLANTA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA
82,2020-01-01,3.203308e+10,1.930613e+10,7.348546e+09,1.944240e+09,3.143455e+09,1.330718e+10,7.359517e+09,1.769962e+09,1.029642e+09,...,9.527461e+09,2.452806e+10,4.371402e+09,2.488187e+09,1.523502e+11,1.197246e+10,1.682974e+09,1.114483e+10,6.673463e+09,9.768665e+08
83,2020-02-01,2.927086e+10,5.153644e+09,5.554978e+09,1.918214e+09,3.533218e+09,1.292674e+10,3.055977e+09,1.098218e+09,1.544896e+09,...,6.958496e+09,1.054037e+10,4.097118e+09,1.729046e+09,5.783372e+10,1.057235e+10,1.604910e+09,1.103541e+10,8.496291e+09,6.988247e+08
84,2020-03-01,2.027045e+10,8.144119e+09,7.102875e+09,1.975291e+09,3.293004e+09,1.220342e+10,3.922640e+09,8.428770e+08,1.147566e+09,...,6.841287e+09,1.350159e+10,4.079455e+09,1.862012e+09,6.088434e+10,1.026033e+10,1.323017e+09,1.659822e+10,9.802661e+09,7.586829e+08
85,2020-04-01,2.126886e+10,8.455198e+09,8.929503e+09,2.004366e+09,3.566387e+09,1.283867e+10,5.173181e+09,1.409078e+09,1.759899e+09,...,7.123936e+09,1.118085e+10,4.243158e+09,2.132902e+09,8.429812e+10,1.663655e+10,1.395267e+09,2.538684e+10,2.492821e+10,8.317438e+08
86,2020-05-01,2.517095e+10,9.302880e+09,8.562890e+09,2.098276e+09,3.610450e+09,1.306803e+10,5.307335e+09,1.869578e+09,2.956764e+09,...,7.793079e+09,1.570667e+10,4.896909e+09,2.143639e+09,1.032899e+11,1.843049e+10,1.481693e+09,2.829947e+10,2.523111e+10,8.881918e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,2025-09-01,4.219560e+10,4.311046e+09,2.281391e+09,4.196104e+09,5.038566e+09,1.493503e+10,1.668252e+09,3.250582e+09,1.596583e+09,...,4.527681e+09,4.632354e+10,5.701145e+09,5.553172e+09,9.385885e+10,3.119236e+10,8.257982e+08,2.837924e+10,1.846899e+10,9.911326e+08
151,2025-10-01,3.296524e+10,2.985446e+09,2.022686e+09,4.011284e+09,5.156462e+09,1.664953e+10,1.497044e+09,3.162083e+09,1.447335e+09,...,3.461418e+09,4.899533e+10,6.215231e+09,5.449996e+09,8.001666e+10,3.120452e+10,4.838548e+08,2.475935e+10,2.706939e+10,9.842681e+08
152,2025-11-01,2.787657e+10,5.009670e+09,2.854232e+09,3.820589e+09,5.160095e+09,2.067290e+10,1.551335e+09,2.959699e+09,1.601224e+09,...,3.595242e+09,3.691386e+10,6.435778e+09,4.722561e+09,6.578819e+10,3.181063e+10,8.503191e+08,2.334741e+10,3.605914e+10,5.706928e+08
153,2025-12-01,1.505901e+10,7.015042e+09,3.018519e+09,4.054325e+09,3.583458e+09,1.798246e+10,2.193442e+09,3.572012e+09,1.467438e+09,...,2.203794e+09,3.414109e+10,6.177664e+09,5.095271e+09,6.285240e+10,2.097690e+10,6.980721e+08,2.047083e+10,2.390173e+10,5.918078e+08
154,2026-01-01,1.288131e+10,1.042724e+10,2.474550e+09,3.910857e+09,4.236795e+09,2.077105e+10,1.976609e+09,3.990784e+09,1.918578e+09,...,3.084249e+09,2.763569e+10,5.668289e+09,5.563521e+09,8.538441e+10,1.998263e+10,9.253710e+08,2.696033e+10,3.130814e+10,7.290227e+08

In [ ]:
df_activos_liquidos.to_excel("activos_liquidos_coops.xlsx", index=False)

2. Extraer histórico del IRL

In [ ]:
irl_banks = pd.read_excel("Histórico_IRL - copia.xlsx")
irl_banks

,Fecha,Tipo y código de entidad,Nombre Entidad,ALM PromedioMes,RLN PromedioMes,IRL
0,2020-03-31,1-1,Banco de Bogotá,1.378050e+10,9.218121e+09,1.495
1,2020-03-31,1-12,Banco GNB Sudameris,7.452656e+09,3.072263e+09,2.426
2,2020-03-31,1-13,BBVA Colombia,1.336877e+10,5.524700e+09,2.42
3,2020-03-31,1-2,Banco Popular,3.307329e+09,2.078626e+09,1.591
4,2020-03-31,1-23,Banco de Occidente,6.776300e+09,2.924886e+09,2.317
...,...,...,...,...,...,...
1436,2022-12-31,32-1,Cooperativa Financiera de Antioquia,9.813516e+07,4.652527e+07,2.109287
1437,2022-12-31,32-2,JFK Cooperativa Financiera,1.701561e+08,5.743336e+07,2.96267
1438,2022-12-31,32-3,Coofinep,5.994189e+07,4.029505e+07,1.487575
1439,2022-12-31,32-4,Cotrafa,1.461325e+08,7.876196e+07,1.85537
1440,2022-12-31,32-5,Confiar,1.799653e+08,1.235760e+08,1.456313

In [ ]:
df_activos_liquidos["fecha_mes"] = df_activos_liquidos["fecha"].dt.to_period("M")
irl_banks["fecha_mes"] = irl_banks["Fecha"].dt.to_period("M")

/tmp/ipykernel_16275/3404885508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_activos_liquidos["fecha_mes"] = df_activos_liquidos["fecha"].dt.to_period("M")

In [ ]:
fechas_comunes = set(df_activos_liquidos["fecha_mes"]) & set(irl_banks["fecha_mes"])

In [ ]:
print(fechas_comunes)

{Period('2021-06', 'M'), Period('2022-05', 'M'), Period('2021-08', 'M'), Period('2020-07', 'M'), Period('2020-09', 'M'), Period('2022-07', 'M'), Period('2022-09', 'M'), Period('2021-10', 'M'), Period('2021-01', 'M'), Period('2021-12', 'M'), Period('2020-11', 'M'), Period('2022-11', 'M'), Period('2020-04', 'M'), Period('2021-03', 'M'), Period('2022-02', 'M'), Period('2020-06', 'M'), Period('2021-05', 'M'), Period('2020-08', 'M'), Period('2022-04', 'M'), Period('2021-07', 'M'), Period('2022-06', 'M'), Period('2021-09', 'M'), Period('2020-10', 'M'), Period('2022-08', 'M'), Period('2021-04', 'M'), Period('2020-12', 'M'), Period('2022-10', 'M'), Period('2022-01', 'M'), Period('2021-11', 'M'), Period('2020-03', 'M'), Period('2021-02', 'M'), Period('2022-12', 'M'), Period('2020-05', 'M'), Period('2022-03', 'M')}

In [ ]:
df_coop = df_activos_liquidos[
    df_activos_liquidos["fecha_mes"].isin(fechas_comunes)
].sort_values("fecha_mes")

df_bancos = irl_banks[
    irl_banks["fecha_mes"].isin(fechas_comunes)
].sort_values("fecha_mes")

In [ ]:
import numpy as np
import pandas as pd

# Filtrar desde marzo 2020
df_coop = df_coop[df_coop["fecha_mes"] >= "2020-03"]
df_bancos = df_bancos[df_bancos["fecha_mes"] >= "2020-03"]

# columnas cooperativas
cols_excluir = ["fecha", "fecha_mes"]
coop_nombres = [col for col in df_coop.columns if col not in cols_excluir]

# asegurar numéricos
df_coop[coop_nombres] = df_coop[coop_nombres].apply(pd.to_numeric, errors="coerce")
df_bancos["ALM PromedioMes"] = pd.to_numeric(df_bancos["ALM PromedioMes"], errors="coerce")

resultados = []

# iterar por fecha
for fecha in df_coop["fecha_mes"].unique():

    df_coop_mes = df_coop[df_coop["fecha_mes"] == fecha]
    df_bancos_mes = df_bancos[df_bancos["fecha_mes"] == fecha]

    # valores de bancos en ese mes
    bancos_mes = df_bancos_mes[["Nombre Entidad", "ALM PromedioMes"]].dropna()

    for coop in coop_nombres:
        valor_coop = df_coop_mes[coop].values[0]

        if np.isnan(valor_coop):
            continue

        mejor_banco = None
        mejor_distancia = np.inf
        mejor_valor_banco = None

        # comparar contra TODOS los bancos de ese mes
        for _, row in bancos_mes.iterrows():
            banco = row["Nombre Entidad"]
            valor_banco = row["ALM PromedioMes"]

            distancia = abs(valor_coop - valor_banco)

            if distancia < mejor_distancia:
                mejor_distancia = distancia
                mejor_banco = banco
                mejor_valor_banco = valor_banco

        resultados.append({
            "fecha_mes": fecha,
            "cooperativa": coop,
            "valor_coop": valor_coop,
            "banco_mas_parecido": mejor_banco,
            "valor_banco": mejor_valor_banco,
            "distancia": mejor_distancia
        })

df_matching = pd.DataFrame(resultados)

In [ ]:
df_matching

,fecha_mes,cooperativa,valor_coop,banco_mas_parecido,valor_banco,distancia
0,2020-03,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.027045e+10,Bancolombia,1.851019e+10,1.760258e+09
1,2020-03,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENES...,8.144119e+09,Banco GNB Sudameris,7.452656e+09,6.914630e+08
2,2020-03,COOPERATIVA PARA EL BIENESTAR SOCIAL,7.102875e+09,Banco de Occidente,6.776300e+09,3.265745e+08
3,2020-03,COOPERATIVA FINANCIERA SAN FRANCISCO,1.975291e+09,AV Villas,1.813395e+09,1.618960e+08
4,2020-03,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL C...,3.293004e+09,Banco Popular,3.307329e+09,1.432539e+07
...,...,...,...,...,...,...
2953,2022-12,COOPERATIVA BELEN AHORRO Y CREDITO,5.395926e+09,Scotiabank Colpatria S.A.,5.385472e+09,1.045359e+07
2954,2022-12,COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS,2.809681e+08,Mibanco S.A.,2.803724e+08,5.956302e+05
2955,2022-12,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS ...,1.269489e+10,BBVA Colombia,1.288028e+10,1.853855e+08
2956,2022-12,COOPERATIVA DE AHORRO Y CREDITO COLANTA,8.335767e+09,Banco GNB Sudameris,8.814007e+09,4.782395e+08
2957,2022-12,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,5.468121e+08,Banco Pichincha S.A.,5.251730e+08,2.163916e+07

Validación

In [ ]:
df_test_row = df_activos_liquidos.loc[df_activos_liquidos["fecha"] == "2022-12-01"]
df_test_col = df_test_row["COOPERATIVA DE AHORRO Y CREDITO COLANTA"]
df_test_col

117    8.335767e+09
Name: COOPERATIVA DE AHORRO Y CREDITO COLANTA, dtype: float64

In [ ]:
df_resultado = pd.merge(
    df_matching,
    irl_banks[["fecha_mes", "Nombre Entidad", "IRL"]],
    left_on=["fecha_mes", "banco_mas_parecido"],
    right_on=["fecha_mes", "Nombre Entidad"],
    how="left"
)

In [ ]:
df_resultado

,fecha_mes,cooperativa,valor_coop,banco_mas_parecido,valor_banco,distancia,Nombre Entidad,IRL
0,2020-03,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.027045e+10,Bancolombia,1.851019e+10,1.760258e+09,Bancolombia,2.443
1,2020-03,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENES...,8.144119e+09,Banco GNB Sudameris,7.452656e+09,6.914630e+08,Banco GNB Sudameris,2.426
2,2020-03,COOPERATIVA PARA EL BIENESTAR SOCIAL,7.102875e+09,Banco de Occidente,6.776300e+09,3.265745e+08,Banco de Occidente,2.317
3,2020-03,COOPERATIVA FINANCIERA SAN FRANCISCO,1.975291e+09,AV Villas,1.813395e+09,1.618960e+08,AV Villas,1.273
4,2020-03,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL C...,3.293004e+09,Banco Popular,3.307329e+09,1.432539e+07,Banco Popular,1.591
...,...,...,...,...,...,...,...,...
2953,2022-12,COOPERATIVA BELEN AHORRO Y CREDITO,5.395926e+09,Scotiabank Colpatria S.A.,5.385472e+09,1.045359e+07,Scotiabank Colpatria S.A.,3.700938
2954,2022-12,COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS,2.809681e+08,Mibanco S.A.,2.803724e+08,5.956302e+05,Mibanco S.A.,2.354543
2955,2022-12,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS ...,1.269489e+10,BBVA Colombia,1.288028e+10,1.853855e+08,BBVA Colombia,1.696709
2956,2022-12,COOPERATIVA DE AHORRO Y CREDITO COLANTA,8.335767e+09,Banco GNB Sudameris,8.814007e+09,4.782395e+08,Banco GNB Sudameris,2.015326
2957,2022-12,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,5.468121e+08,Banco Pichincha S.A.,5.251730e+08,2.163916e+07,Banco Pichincha S.A.,1.516988

In [ ]:
df_resultado.to_excel("df_matching.xlsx", index=False)