In [20]:
import pandas as pd

In [21]:
df_coperativas = pd.read_excel("../tablas/registros.xlsx")
df_coperativas

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2014,1,1.500449
1,2,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2014,1,1.310736
2,3,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2014,1,1.188087
3,4,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,1.588034
4,5,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,1.481415
...,...,...,...,...,...,...
213305,213306,Indicador de Riesgo de Liquidez - IRL,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,2025,12,0.000000
213306,213307,Indicador de Riesgo de Liquidez - IRL,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO ...,2025,12,0.000000
213307,213308,Indicador de Riesgo de Liquidez - IRL,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,2025,12,0.000000
213308,213309,Indicador de Riesgo de Liquidez - IRL,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURS...,2025,12,0.000000
213309,213310,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2025,12,0.000000

In [22]:
df_irl = pd.read_excel("../tablas/df_matching.xlsx")
df_irl

,fecha_mes,cooperativa,valor_coop,banco_mas_parecido,valor_banco,distancia,Nombre Entidad,IRL
0,2020-03,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.027045e+10,Bancolombia,1.851019e+10,1.760258e+09,Bancolombia,2.443
1,2020-03,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENES...,8.144119e+09,Banco GNB Sudameris,7.452656e+09,6.914630e+08,Banco GNB Sudameris,2.426
2,2020-03,COOPERATIVA PARA EL BIENESTAR SOCIAL,7.102875e+09,Banco de Occidente,6.776300e+09,3.265745e+08,Banco de Occidente,2.317
3,2020-03,COOPERATIVA FINANCIERA SAN FRANCISCO,1.975291e+09,AV Villas,1.813395e+09,1.618960e+08,AV Villas,1.273
4,2020-03,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL C...,3.293004e+09,Banco Popular,3.307329e+09,1.432539e+07,Banco Popular,1.591
...,...,...,...,...,...,...,...,...
2953,2022-12,COOPERATIVA BELEN AHORRO Y CREDITO,5.395926e+09,Scotiabank Colpatria S.A.,5.385472e+09,1.045359e+07,Scotiabank Colpatria S.A.,3.700938
2954,2022-12,COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS,2.809681e+08,Mibanco S.A.,2.803724e+08,5.956302e+05,Mibanco S.A.,2.354543
2955,2022-12,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS ...,1.269489e+10,BBVA Colombia,1.288028e+10,1.853855e+08,BBVA Colombia,1.696709
2956,2022-12,COOPERATIVA DE AHORRO Y CREDITO COLANTA,8.335767e+09,Banco GNB Sudameris,8.814007e+09,4.782395e+08,Banco GNB Sudameris,2.015326
2957,2022-12,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,5.468121e+08,Banco Pichincha S.A.,5.251730e+08,2.163916e+07,Banco Pichincha S.A.,1.516988

In [23]:
df_irl["fecha_mes"] = df_irl["fecha_mes"].astype(str)

df_irl["ano"] = df_irl["fecha_mes"].str[:4].astype(int)
df_irl["mes"] = df_irl["fecha_mes"].str[5:7].astype(int)

In [24]:
df_coop_irl = df_coperativas[
    df_coperativas["ID_indicador"] == "Indicador de Riesgo de Liquidez - IRL"
].copy()

In [37]:
df_merge = pd.merge(
    df_coop_irl,
    df_irl[["cooperativa", "ano", "mes", "IRL"]],
    left_on=["ID_cooperativa", "ano", "mes"],
    right_on=["cooperativa", "ano", "mes"],
    how="inner"   
)

In [38]:
df_merge = df_merge.drop(["cooperativa", "valor"], axis=1)

In [40]:
df_merge = df_merge.rename(columns={"IRL": "valor"})

In [41]:
df_merge

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,207151,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA CREDICOOP,2020,3,1.591
1,207152,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA PETROLERA,2020,3,1.425
2,207153,Indicador de Riesgo de Liquidez - IRL,CASA NACIONAL DEL PROFESOR,2020,3,5.279
3,207154,Indicador de Riesgo de Liquidez - IRL,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2020,3,2.42
4,207155,Indicador de Riesgo de Liquidez - IRL,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2020,3,2.136
...,...,...,...,...,...,...
2953,210138,Indicador de Riesgo de Liquidez - IRL,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,2022,12,1.711657
2954,210139,Indicador de Riesgo de Liquidez - IRL,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO ...,2022,12,2.96267
2955,210140,Indicador de Riesgo de Liquidez - IRL,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,2022,12,2.701807
2956,210141,Indicador de Riesgo de Liquidez - IRL,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURS...,2022,12,1.614583
2957,210142,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2022,12,2.701807

Concatenar tablas

In [42]:
df_total = pd.concat([df_coperativas, df_merge], ignore_index=True)

In [43]:
df_total = df_total.drop_duplicates(
    subset=["ano", "mes", "ID_indicador", "ID_cooperativa"],
    keep="last"
)

In [44]:
df_total

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2014,1,1.500449
1,2,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2014,1,1.310736
2,3,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2014,1,1.188087
3,4,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,1.588034
4,5,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,1.481415
...,...,...,...,...,...,...
216263,210138,Indicador de Riesgo de Liquidez - IRL,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,2022,12,1.711657
216264,210139,Indicador de Riesgo de Liquidez - IRL,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO ...,2022,12,2.96267
216265,210140,Indicador de Riesgo de Liquidez - IRL,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,2022,12,2.701807
216266,210141,Indicador de Riesgo de Liquidez - IRL,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURS...,2022,12,1.614583
216267,210142,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2022,12,2.701807

In [45]:
df_total.to_excel("registros_irl_actualizado.xlsx")