# Implementación PCA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Registros de la BD

In [2]:
import pymysql

Connection successful!

### Elaborar tabla con los respectivos nombres de indicadores

In [4]:
indicadores = pd.read_sql("SELECT * FROM indicador", conn)
id_indicador = indicadores["ID_indicador"].tolist()
nombre_indicador = indicadores["nombre"].tolist()
dict_indicadores = dict(zip(id_indicador, nombre_indicador))
print(dict_indicadores)

/tmp/ipykernel_16644/3216715992.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  indicadores = pd.read_sql("SELECT * FROM indicador", conn)

{1: 'Quebranto Patrimonial', 3: 'Relación entre Aportes sociales mínimos no reducibles y Capital Social', 4: 'Relación entre el Capital Institucional y el Activo Total', 2: 'Relación Solvencia', 8: 'Activo Productivo', 6: 'Indicador de calidad por riesgo', 7: 'Indicador de calidad por riesgo con castigos', 5: 'Indicador de Cobertura de la Cartera Total en Riesgo', 9: 'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo', 10: 'Estructura de Balance', 11: 'Indicador de Margen Financiero de Operación', 12: 'Indicador de Margen Operacional', 13: 'Indicador de relación entre las obligaciones financieras y el pasivo total', 14: 'Indicador de margen neto', 15: 'Indicador de rentabilidad sobre el capital invertido - ROIC', 16: 'Indicador de rentabilidad sobre recursos propios - ROE', 17: 'Indicador de Riesgo de Liquidez - IRL'}

In [5]:
cooperativas = pd.read_sql("SELECT * FROM cooperativa", conn)
id_cooperativa = cooperativas["ID_cooperativa"].tolist()
nombre_cooperativa = cooperativas["nombre"].tolist()
dict_cooperativas = dict(zip(id_cooperativa, nombre_cooperativa))
print(dict_cooperativas)

{1: 'CAJA COOPERATIVA CREDICOOP', 2: 'CAJA COOPERATIVA PETROLERA', 3: 'CASA NACIONAL DEL PROFESOR', 4: 'COOPANTEX COOPERATIVA DE AHORRO Y CREDITO', 5: 'COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.', 6: 'COOPERATIVA BELEN AHORRO Y CREDITO', 7: 'COOPERATIVA CALDENSE DEL PROFESOR', 8: 'COOPERATIVA DE AHORRO Y CREDITO BERLIN', 9: 'COOPERATIVA DE AHORRO Y CREDITO COLANTA', 10: 'COOPERATIVA DE AHORRO Y CREDITO CONGENTE', 11: 'COOPERATIVA DE AHORRO Y CREDITO COOMPARTIR', 12: 'COOPERATIVA DE AHORRO Y CREDITO COOTRAIPI', 13: 'COOPERATIVA DE AHORRO Y CREDITO COOYAMOR', 14: 'COOPERATIVA DE AHORRO Y CREDITO CREAFAM', 15: 'COOPERATIVA DE AHORRO Y CREDITO CREAR LTDA CREARCOP', 16: 'COOPERATIVA DE AHORRO Y CREDITO DE AIPE', 17: 'COOPERATIVA DE AHORRO Y CREDITO DE CHIPAQUE', 18: 'COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS', 19: 'COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA', 20: 'COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA', 21: 'COOPERATIVA DE AHORRO Y CREDITO DE TENJO', 22: 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES UNIDOS POR EL PROGRESO', 23: 'COOPERATIVA DE AHORRO Y CREDITO DEL FUTURO', 24: 'COOPERATIVA DE AHORRO Y CREDITO DEL NUCLEO FAMILIAR DE LOS TRAB.DE ECP.LTDA', 25: 'COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS', 26: 'COOPERATIVA DE AHORRO Y CREDITO LA GRANJA LTDA.', 27: 'COOPERATIVA DE AHORRO Y CREDITO LA PLAYA DE BELEN LTDA', 28: 'COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL', 29: 'COOPERATIVA DE AHORRO Y CREDITO RIACHON LTDA.', 30: 'COOPERATIVA DE AHORRO Y CREDITO SAN MIGUEL', 31: 'COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO', 32: 'COOPERATIVA DE AHORRO Y CREDITO TABACALERA Y AGROPECUARIA LTDA', 33: 'COOPERATIVA DE AHORRO Y CREDITO UNIVERSIDAD SANTO TOMAS', 34: 'COOPERATIVA DE EMPLEADOS DEL SECTOR COOPERATIVO LTDA.', 35: 'COOPERATIVA DE EMPLEADOS SURAMERICANA', 36: 'COOPERATIVA DE FOMENTO E INVERSION SOCIAL POPULAR', 37: 'COOPERATIVA DE LA UNIVERSIDAD NACIONAL DE COLOMBIA', 38: 'COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS', 39: 'COOPERATIVA DE LOS TRABAJADORES DEL INSTITUTO DE LOS SEGUROS SOCIALES', 40: 'COOPERATIVA DE MUJERES PARA LA PROMOCION INTEGRAL', 41: 'COOPERATIVA DE PROFESIONALES DE CALDAS', 42: 'COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA', 43: 'COOPERATIVA DE PROMOCION SOCIAL', 44: 'COOPERATIVA DE TRABAJADORES DE BAVARIA DIRECCION Y VENTAS LTDA', 45: 'COOPERATIVA DE TRABAJADORES DE LA EDUCACION DEL RISARALDA', 46: 'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DEPARTAMENTALES DE ANTIOQU', 47: 'COOPERATIVA DE TRABAJADORES DEL SENA', 48: 'COOPERATIVA DE TRABAJADORES DEPARTAMENTALES DE ANTIOQUIA', 49: 'COOPERATIVA DE TRABAJADORES Y PENSIONADOS DE LA E.A.A.B.', 50: 'COOPERATIVA DE TT DE EL COLOMBIANO LTDA.', 51: 'COOPERATIVA DE YARUMAL', 52: 'COOPERATIVA DEL MAGISTERIO', 53: 'COOPERATIVA DIOCESANA DEL CLERO LTDA', 54: 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA', 55: 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO DE LA ORINOQUIA', 56: 'COOPERATIVA FINANCIERA CAFETERA', 57: 'COOPERATIVA FINANCIERA SAN FRANCISCO', 58: 'COOPERATIVA FRATERNIDAD SACERDOTAL LTDA', 59: 'COOPERATIVA INTEGRAL AGROPECUARIA LA PAZ LTDA', 60: 'COOPERATIVA INTEGRAL PARA EL DESARROLLO SOCIAL Y ECONOMICO DE TEORAMA', 61: 'COOPERATIVA LA ROSA', 62: 'COOPERATIVA LATINOAMERICANA DE AHORRO Y CREDITO', 63: 'COOPERATIVA LEON XIII DE MACEO LTDA', 64: 'COOPERATIVA MEDICA DE ANTIOQUIA LTDA', 65: 'COOPERATIVA MULTIACTIVA ANTONIO JOSE JARAMILLO TOBON', 66: 'COOPERATIVA MULTIACTIVA COOMONOMEROS', 67: 'COOPERATIVA MULTIACTIVA DE EL PAUJIL CAQUETA LIMITADA', 68: 'COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA', 69: 'COOPERATIVA MULTIACTIVA DE LOS TRABAJADORES DEL ISS', 70: 'COOPERATIVA MULTIACTIVA DE PROFESIONALES DE SANTANDER LTDA', 71: 'COOPERATIVA MULTIACTIVA DEL GUAINIA', 72: 'COOPERATIVA MULTIACTIVA DEL INEM DE IBAGUE', 73: 'COOPERATIVA MULTIACTIVA EL BAGRE LTDA', 74: 'COOPERATIVA MULTIEMPRESAS', 75: 'COOPERATIVA MULTISERVICIOS BARICHARA LTDA', 76: 'COOPERATIVA NACIONAL EDUCATIVA DE AHORRO Y CREDITO', 77: 'COOPERATIVA PARA EL BIENESTAR SOCIAL', 78: 'COOPERATIVA SAN SIMON', 79: 'COOPERATIVA SAN VICENTE DE PAUL LTDA.', 80: 'COOPERATIVA TELEPOSTAL LTDA', 81: 'COOPERATIVA TEXAS LTDA', 82: 'COPERATIVA INDEPENDIENTE DE EMPLEADOS DE ANTIOQUIA', 83: 'COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA', 84: 'COPROCENVA COOPERATIVA DE AHORRO Y CREDITO', 85: 'EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.', 86: 'FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS', 87: 'GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES', 88: 'MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA'}

/tmp/ipykernel_16644/1852280459.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cooperativas = pd.read_sql("SELECT * FROM cooperativa", conn)

In [6]:
registros = pd.read_sql("SELECT * FROM registro", conn)

/tmp/ipykernel_16644/1473806713.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  registros = pd.read_sql("SELECT * FROM registro", conn)

In [7]:
registros["ID_indicador"] = registros["ID_indicador"].map(dict_indicadores)
registros["ID_cooperativa"] = registros["ID_cooperativa"].map(dict_cooperativas)
registros.head()

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2014,1,1.500449
1,2,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2014,1,1.310736
2,3,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2014,1,1.188087
3,4,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,1.588034
4,5,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,1.481415

In [8]:
registros.to_excel("registros.xlsx", index=False)

## Aplicar PCA a todos los indicadores

In [32]:
registros.loc[(registros["ID_indicador"]=="Indicador de Riesgo de Liquidez - IRL")&(registros["valor"]!=0)]

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
200638,200639,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA CREDICOOP,2014,1,227.86
200639,200640,Indicador de Riesgo de Liquidez - IRL,CAJA COOPERATIVA PETROLERA,2014,1,227.86
200640,200641,Indicador de Riesgo de Liquidez - IRL,CASA NACIONAL DEL PROFESOR,2014,1,227.86
200641,200642,Indicador de Riesgo de Liquidez - IRL,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,227.86
200642,200643,Indicador de Riesgo de Liquidez - IRL,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,227.86
...,...,...,...,...,...,...
212865,212866,Indicador de Riesgo de Liquidez - IRL,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,2025,7,216.73
212866,212867,Indicador de Riesgo de Liquidez - IRL,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO ...,2025,7,216.73
212867,212868,Indicador de Riesgo de Liquidez - IRL,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,2025,7,216.73
212868,212869,Indicador de Riesgo de Liquidez - IRL,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURS...,2025,7,216.73
212869,212870,Indicador de Riesgo de Liquidez - IRL,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA",2025,7,216.73

### Cooperativas sectorizadas

In [41]:
nombres_coops = list(dict_cooperativas.values())

In [44]:
print(nombres_coops)

['CAJA COOPERATIVA CREDICOOP', 'CAJA COOPERATIVA PETROLERA', 'CASA NACIONAL DEL PROFESOR', 'COOPANTEX COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.', 'COOPERATIVA BELEN AHORRO Y CREDITO', 'COOPERATIVA CALDENSE DEL PROFESOR', 'COOPERATIVA DE AHORRO Y CREDITO BERLIN', 'COOPERATIVA DE AHORRO Y CREDITO COLANTA', 'COOPERATIVA DE AHORRO Y CREDITO CONGENTE', 'COOPERATIVA DE AHORRO Y CREDITO COOMPARTIR', 'COOPERATIVA DE AHORRO Y CREDITO COOTRAIPI', 'COOPERATIVA DE AHORRO Y CREDITO COOYAMOR', 'COOPERATIVA DE AHORRO Y CREDITO CREAFAM', 'COOPERATIVA DE AHORRO Y CREDITO CREAR LTDA CREARCOP', 'COOPERATIVA DE AHORRO Y CREDITO DE AIPE', 'COOPERATIVA DE AHORRO Y CREDITO DE CHIPAQUE', 'COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS', 'COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA', 'COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA', 'COOPERATIVA DE AHORRO Y CREDITO DE TENJO', 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES UNIDOS POR EL PROGRESO', 'COOPERATIVA DE AHORRO Y CREDITO DEL FUTURO', 'COOPERATIVA DE AHORRO Y CREDITO DEL NUCLEO FAMILIAR DE LOS TRAB.DE ECP.LTDA', 'COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS', 'COOPERATIVA DE AHORRO Y CREDITO LA GRANJA LTDA.', 'COOPERATIVA DE AHORRO Y CREDITO LA PLAYA DE BELEN LTDA', 'COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL', 'COOPERATIVA DE AHORRO Y CREDITO RIACHON LTDA.', 'COOPERATIVA DE AHORRO Y CREDITO SAN MIGUEL', 'COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO', 'COOPERATIVA DE AHORRO Y CREDITO TABACALERA Y AGROPECUARIA LTDA', 'COOPERATIVA DE AHORRO Y CREDITO UNIVERSIDAD SANTO TOMAS', 'COOPERATIVA DE EMPLEADOS DEL SECTOR COOPERATIVO LTDA.', 'COOPERATIVA DE EMPLEADOS SURAMERICANA', 'COOPERATIVA DE FOMENTO E INVERSION SOCIAL POPULAR', 'COOPERATIVA DE LA UNIVERSIDAD NACIONAL DE COLOMBIA', 'COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS', 'COOPERATIVA DE LOS TRABAJADORES DEL INSTITUTO DE LOS SEGUROS SOCIALES', 'COOPERATIVA DE MUJERES PARA LA PROMOCION INTEGRAL', 'COOPERATIVA DE PROFESIONALES DE CALDAS', 'COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA', 'COOPERATIVA DE PROMOCION SOCIAL', 'COOPERATIVA DE TRABAJADORES DE BAVARIA DIRECCION Y VENTAS LTDA', 'COOPERATIVA DE TRABAJADORES DE LA EDUCACION DEL RISARALDA', 'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DEPARTAMENTALES DE ANTIOQU', 'COOPERATIVA DE TRABAJADORES DEL SENA', 'COOPERATIVA DE TRABAJADORES DEPARTAMENTALES DE ANTIOQUIA', 'COOPERATIVA DE TRABAJADORES Y PENSIONADOS DE LA E.A.A.B.', 'COOPERATIVA DE TT DE EL COLOMBIANO LTDA.', 'COOPERATIVA DE YARUMAL', 'COOPERATIVA DEL MAGISTERIO', 'COOPERATIVA DIOCESANA DEL CLERO LTDA', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO DE LA ORINOQUIA', 'COOPERATIVA FINANCIERA CAFETERA', 'COOPERATIVA FINANCIERA SAN FRANCISCO', 'COOPERATIVA FRATERNIDAD SACERDOTAL LTDA', 'COOPERATIVA INTEGRAL AGROPECUARIA LA PAZ LTDA', 'COOPERATIVA INTEGRAL PARA EL DESARROLLO SOCIAL Y ECONOMICO DE TEORAMA', 'COOPERATIVA LA ROSA', 'COOPERATIVA LATINOAMERICANA DE AHORRO Y CREDITO', 'COOPERATIVA LEON XIII DE MACEO LTDA', 'COOPERATIVA MEDICA DE ANTIOQUIA LTDA', 'COOPERATIVA MULTIACTIVA ANTONIO JOSE JARAMILLO TOBON', 'COOPERATIVA MULTIACTIVA COOMONOMEROS', 'COOPERATIVA MULTIACTIVA DE EL PAUJIL CAQUETA LIMITADA', 'COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA', 'COOPERATIVA MULTIACTIVA DE LOS TRABAJADORES DEL ISS', 'COOPERATIVA MULTIACTIVA DE PROFESIONALES DE SANTANDER LTDA', 'COOPERATIVA MULTIACTIVA DEL GUAINIA', 'COOPERATIVA MULTIACTIVA DEL INEM DE IBAGUE', 'COOPERATIVA MULTIACTIVA EL BAGRE LTDA', 'COOPERATIVA MULTIEMPRESAS', 'COOPERATIVA MULTISERVICIOS BARICHARA LTDA', 'COOPERATIVA NACIONAL EDUCATIVA DE AHORRO Y CREDITO', 'COOPERATIVA PARA EL BIENESTAR SOCIAL', 'COOPERATIVA SAN SIMON', 'COOPERATIVA SAN VICENTE DE PAUL LTDA.', 'COOPERATIVA TELEPOSTAL LTDA', 'COOPERATIVA TEXAS LTDA', 'COPERATIVA INDEPENDIENTE DE EMPLEADOS DE ANTIOQUIA', 'COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA', 'COPROCENVA COOPERATIVA DE AHORRO Y CREDITO', 'EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.', 'FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS', 'GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES', 'MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA']

In [42]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
import pandas as pd

def pesos_pca_grupo_coops(
    df,
    lista_coops,
    col_nombre="ID_cooperativa",
    n_componentes=3
):
    
    # filtrar cooperativas
    df_filtrado = df[df[col_nombre].isin(lista_coops)]
    
    if df_filtrado.empty:
        raise ValueError("No hay datos para las cooperativas indicadas")
    
    # pivot (matriz indicadores)
    df_pivot = df_filtrado.pivot_table(
        index=col_nombre,
        columns="ID_indicador",
        values="valor",
        aggfunc="mean"
    )
    
    # imputar faltantes
    imputer = SimpleImputer(strategy="mean")
    X_imputed = imputer.fit_transform(df_pivot)
    
    # escalar
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X_imputed)
    
    # PCA
    pca = PCA(n_components=min(n_componentes, df_pivot.shape[1]))
    pca.fit(X_scaled)
    
    loadings = pd.DataFrame(
        pca.components_.T,
        index=df_pivot.columns
    )
    
    pesos = (loadings**2).mean(axis=1)
    
    # porcentaje
    pesos = (pesos / pesos.sum()) * 100
    
    return pesos.sort_values(ascending=False)

In [43]:
pesos_pca_grupo_coops(df=registros, lista_coops=nombres_coops)

ID_indicador
Quebranto Patrimonial                                                                     12.449654
Indicador de Margen Financiero de Operación                                               11.644880
Relación entre el Capital Institucional y el Activo Total                                 10.563098
Estructura de Balance                                                                     10.560369
Indicador de rentabilidad sobre recursos propios - ROE                                    10.361907
Relación entre Aportes sociales mínimos no reducibles y Capital Social                     7.511503
Indicador de calidad por riesgo                                                            7.344631
Indicador de rentabilidad sobre el capital invertido - ROIC                                6.683072
Indicador de margen neto                                                                   6.303224
Indicador de Margen Operacional                                                            5.975950
Indicador de calidad por riesgo con castigos                                               4.220932
Indicador de relación entre las obligaciones financieras y el pasivo total                 2.179970
Indicador de Cobertura de la Cartera Total en Riesgo                                       2.010379
Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo     1.106872
Activo Productivo                                                                          1.083558
Indicador de Riesgo de Liquidez - IRL                                                      0.000000
Relación Solvencia                                                                         0.000000
dtype: float64