# Revisar los indicadores de Earnings
*Porque no se están guardando en el excel conjunto*

--web scraping

1. Listar los archivos de excel
2. Construir dataframe con esos excels
3. Aplicar transformaciones al dataframe
4. Construir csv conjunto de todos los valores de las cooperativas 2021-2025

--camel_model_general

5. Cargar coops
6. Ejecutar indicadores para Earnings y construir csv
7. Verificar si se guardan los dos indicadores que faltan (ROE y ROIC)

In [2]:
# revisar los indicadores de Earnings
import pandas as pd

data = pd.read_excel("../tablas/camel/Registros_CAMEL_con_IRL.xlsx")
data.head(3)

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.273373
1,2,2021,1,Relación Solvencia,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0
2,3,2021,1,Relación entre Aportes sociales mínimos no red...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.4039

In [ ]:
# Extraer los indicadores de Earnings
earnings = pd.read_csv("../tablas/camel/Earnings.csv")
earnings.head(3)

In [4]:
# Ajustar estructura de la tabla
# Convertir de formato ancho a largo
registros_earnings = earnings.melt(
    id_vars=['Año', 'Mes', 'índice CAMEL'],
    var_name='ID_cooperativa',
    value_name='valor'
)

# Renombrar columnas
registros_earnings = registros_earnings.rename(columns={
    'Año': 'ano',
    'Mes': 'mes',
    'índice CAMEL': 'ID_indicador'
})

# Crear ID_registro
registros_earnings.insert(
    0,
    'ID_registro',
    range(1, len(registros_earnings) + 1)
)

registros_earnings.head()

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Indicador de margen neto,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.251205
1,2,2021,2,Indicador de margen neto,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.141883
2,3,2021,2,Indicador de rentabilidad sobre el capital inv...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.266753
3,4,2021,2,Indicador de rentabilidad sobre recursos propi...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.614925
4,5,2021,3,Indicador de margen neto,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.244838

In [5]:
# Concatenar con la tabla de registros CAMEL
import pandas as pd

# df1 y df2 tienen las mismas columnas
df_combined = pd.concat([data, registros_earnings], ignore_index=True)

df_result = df_combined.drop_duplicates(
    subset=['ano', 'mes', 'ID_indicador', 'ID_cooperativa'],
    keep='last'
)

In [11]:
df_result.to_excel("../tablas/camel/Registros_CAMEL_con_IRL.xlsx", index=False)