In [1]:
import pandas as pd
import numpy as np

In [6]:
datos_viejos=pd.read_excel("../tablas/registros_solvencia_actualizado.xlsx")
datos_viejos=datos_viejos.drop(columns=["Unnamed: 0"])
datos_viejos=datos_viejos[datos_viejos["ID_indicador"]!='Indicador de Riesgo de Liquidez - IRL']
datos_viejos.columns

Index(['ID_registro', 'ID_indicador', 'ID_cooperativa', 'ano', 'mes', 'valor'], dtype='object')

In [11]:
datos_viejos.head()

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,1,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2014,1,1.500449
1,2,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2014,1,1.310736
2,3,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2014,1,1.188087
3,4,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2014,1,1.588034
4,5,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2014,1,1.481415

In [12]:
datos_viejos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200638 entries, 0 to 213309
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_registro     200638 non-null  int64
 1   ID_indicador    200638 non-null  object
 2   ID_cooperativa  200638 non-null  object
 3   ano             200638 non-null  int64
 4   mes             200638 non-null  int64
 5   valor           200638 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 10.7+ MB

In [7]:
datos_viejos["ID_indicador"].unique()

array(['Quebranto Patrimonial', 'Relación Solvencia',
       'Relación entre Aportes sociales mínimos no reducibles y Capital Social',
       'Relación entre el Capital Institucional y el Activo Total',
       'Indicador de Cobertura de la Cartera Total en Riesgo',
       'Indicador de calidad por riesgo',
       'Indicador de calidad por riesgo con castigos',
       'Activo Productivo',
       'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo',
       'Estructura de Balance',
       'Indicador de Margen Financiero de Operación',
       'Indicador de Margen Operacional',
       'Indicador de relación entre las obligaciones financieras y el pasivo total',
       'Indicador de margen neto',
       'Indicador de rentabilidad sobre el capital invertido - ROIC',
       'Indicador de rentabilidad sobre recursos propios - ROE'],
      dtype=object)

# transformar datos

In [21]:
datos_activos_liquidos=pd.read_excel("../tablas/activos_liquidos_coops.xlsx")
datos_activos_liquidos.head()

,fecha,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA DE AHORRO Y CREDITO PARA EL BIENESTAR SOCIAL,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA,CAJA COOPERATIVA CREDICOOP,COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,...,COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO BERLIN,COOPERATIVA DE AHORRO Y CREDITO DE AIPE,COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA,COOPERATIVA BELEN AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS,COOPERATIVA DE AHORRO Y CREDITO COLANTA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA
0,2020-01-01,3.203308e+10,1.930613e+10,7.348546e+09,1.944240e+09,3.143455e+09,1.330718e+10,7.359517e+09,1.769962e+09,1.029642e+09,...,9.527461e+09,2.452806e+10,4.371402e+09,2.488187e+09,1.523502e+11,11972463032,1.682974e+09,1.114483e+10,6673462753,9.768665e+08
1,2020-02-01,2.927086e+10,5.153644e+09,5.554978e+09,1.918214e+09,3.533218e+09,1.292674e+10,3.055977e+09,1.098218e+09,1.544896e+09,...,6.958496e+09,1.054037e+10,4.097118e+09,1.729046e+09,5.783372e+10,10572353775,1.604910e+09,1.103541e+10,8496290806,6.988247e+08
2,2020-03-01,2.027045e+10,8.144119e+09,7.102875e+09,1.975291e+09,3.293004e+09,1.220342e+10,3.922640e+09,8.428770e+08,1.147566e+09,...,6.841287e+09,1.350159e+10,4.079455e+09,1.862012e+09,6.088434e+10,10260326162,1.323017e+09,1.659822e+10,9802661394,7.586829e+08
3,2020-04-01,2.126886e+10,8.455198e+09,8.929503e+09,2.004366e+09,3.566387e+09,1.283867e+10,5.173181e+09,1.409078e+09,1.759899e+09,...,7.123936e+09,1.118085e+10,4.243158e+09,2.132902e+09,8.429812e+10,16636552633,1.395267e+09,2.538684e+10,24928207947,8.317438e+08
4,2020-05-01,2.517095e+10,9.302880e+09,8.562890e+09,2.098276e+09,3.610450e+09,1.306803e+10,5.307335e+09,1.869578e+09,2.956764e+09,...,7.793079e+09,1.570667e+10,4.896909e+09,2.143639e+09,1.032899e+11,18430492970,1.481693e+09,2.829947e+10,25231114005,8.881918e+08

In [22]:
datos_activos_liquidos_melted = datos_activos_liquidos.melt(id_vars=["fecha"], 
                                                            value_vars=datos_activos_liquidos.columns[1:].tolist(),
                                                            var_name="ID_cooperativa", 
                                                            value_name="valor")

In [23]:
datos_activos_liquidos_melted

,fecha,ID_cooperativa,valor
0,2020-01-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,3.203308e+10
1,2020-02-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.927086e+10
2,2020-03-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.027045e+10
3,2020-04-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.126886e+10
4,2020-05-01,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.517095e+10
...,...,...,...
6346,2025-09-01,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,9.911326e+08
6347,2025-10-01,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,9.842681e+08
6348,2025-11-01,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,5.706928e+08
6349,2025-12-01,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,5.918078e+08
6350,2026-01-01,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO ...,7.290227e+08

In [24]:
datos_activos_liquidos_melted["ID_registro"]=99
datos_activos_liquidos_melted["fecha"]=pd.to_datetime(datos_activos_liquidos_melted["fecha"], format="%Y-%m-%d")
datos_activos_liquidos_melted["ano"]=datos_activos_liquidos_melted["fecha"].dt.year
datos_activos_liquidos_melted["mes"]=datos_activos_liquidos_melted["fecha"].dt.month
datos_activos_liquidos_melted["ID_indicador"]="IRL"
datos_activos_liquidos_melted=datos_activos_liquidos_melted.drop(columns=["fecha"])
datos_activos_liquidos_melted.head()

,ID_cooperativa,valor,ID_registro,ano,mes,ID_indicador
0,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,3.203308e+10,99,2020,1,IRL
1,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.927086e+10,99,2020,2,IRL
2,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.027045e+10,99,2020,3,IRL
3,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.126886e+10,99,2020,4,IRL
4,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD C...,2.517095e+10,99,2020,5,IRL

# unir datos, teniendo en cuenta que fecha minima 2020 y fecha maxima 2025

In [28]:
datos_viejos_mescla=datos_viejos.loc[(datos_viejos["ano"]>=2020)&(datos_viejos["ano"]<=2025)]
datos_activos_liquidos_mescla=datos_activos_liquidos_melted.loc[(datos_activos_liquidos_melted["ano"]>=2020)&(datos_activos_liquidos_melted["ano"]<=2025)]
datos_concatenados=pd.concat([datos_viejos_mescla,datos_activos_liquidos_mescla], ignore_index=True)
datos_concatenados.head()

,ID_registro,ID_indicador,ID_cooperativa,ano,mes,valor
0,25345,Quebranto Patrimonial,CAJA COOPERATIVA CREDICOOP,2020,1,0.0
1,25346,Quebranto Patrimonial,CAJA COOPERATIVA PETROLERA,2020,1,0.0
2,25347,Quebranto Patrimonial,CASA NACIONAL DEL PROFESOR,2020,1,0.0
3,25348,Quebranto Patrimonial,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,2020,1,0.0
4,25349,Quebranto Patrimonial,COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.,2020,1,0.0

In [29]:
datos_concatenados.to_excel("../tablas/registros_irl_para_pca.xlsx", index=False)