# Modelo CAMEL

Usar los csv generados para los indicadores de cada variable y concatenarlos en una misma tabla de registros

In [4]:
import pandas as pd

capital = pd.read_csv("../../tablas/camel/Capital.csv")
assets = pd.read_csv("../../tablas/camel/Assets.csv")
managerial = pd.read_csv("../../tablas/camel/Managerial.csv")
earnings = pd.read_csv("../../tablas/camel/Earnings.csv")
liquidity = pd.read_csv("../../tablas/camel/Liquidity.csv")

registros_camel = pd.concat([capital, assets, managerial, earnings, liquidity], ignore_index=True)
registros_camel.head(4)

,Año,Mes,índice CAMEL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Quebranto Patrimonial,1.273373,1.411881,1.402952,1.176358,1.189875,1.580431,1.440600,...,1.232324,1.230669,1.407583,1.769592,1.777716,1.492571,1.599766,1.139058,2.550899,1.778111
1,2021,1,Relación Solvencia,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,2021,1,Relación entre Aportes sociales mínimos no red...,0.403900,0.895748,0.915331,0.761172,0.215563,0.751721,0.666482,...,0.585939,0.197089,0.884482,0.545074,0.894829,0.760413,0.409011,0.699999,0.463306,0.128358
3,2021,1,Relación entre el Capital Institucional y el A...,0.069203,0.088234,0.079618,0.024763,0.045663,0.088640,0.044706,...,0.010242,0.039672,0.076342,0.092791,0.115116,0.095580,0.183472,0.035557,0.180247,0.203313

Ajustar la estructura de la tabla (mejor)

In [5]:
# Convertir de formato ancho a largo
registros_camel_long = registros_camel.melt(
    id_vars=['Año', 'Mes', 'índice CAMEL'],
    var_name='ID_cooperativa',
    value_name='valor'
)

# Renombrar columnas
registros_camel_long = registros_camel_long.rename(columns={
    'Año': 'ano',
    'Mes': 'mes',
    'índice CAMEL': 'ID_indicador'
})

# Crear ID_registro
registros_camel_long.insert(
    0,
    'ID_registro',
    range(1, len(registros_camel_long) + 1)
)

registros_camel_long.head()

,ID_registro,ano,mes,ID_indicador,ID_cooperativa,valor
0,1,2021,1,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.273373
1,2,2021,1,Relación Solvencia,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.000000
2,3,2021,1,Relación entre Aportes sociales mínimos no red...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.403900
3,4,2021,1,Relación entre el Capital Institucional y el A...,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,0.069203
4,5,2021,2,Quebranto Patrimonial,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,1.267651

In [6]:
registros_camel_long.to_csv("../../tablas/camel/Registros_CAMEL.csv", index=False, encoding="utf-8")